version: '2'

services:
        zoo1:
                image: wurstmeister/zookeeper
                restart: unless-stopped
                hostname: bigdata-zoo1
                ports:
                        - "2181:2181"
                container_name: zookeeper

        kafka:
                image: wurstmeister/kafka:1.0.0
                ports:
                        - "9092:9092"
                environment:
                        KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
                        KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
                        KAFKA_BROKER_ID: 1
                depends_on:
                        - zoo1
                container_name: kafka

