/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leatop.bee.web.po;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ETCPassListAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5455642186345160430L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ETCPassListAvro\",\"namespace\":\"com.leatop.bee.web.po\",\"fields\":[{\"name\":\"recordNo\",\"type\":\"int\"},{\"name\":\"serialNo\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"flagNetRoadID\",\"type\":\"int\"},{\"name\":\"flagRoadID\",\"type\":\"int\"},{\"name\":\"flagID\",\"type\":\"int\"},{\"name\":\"obuType\",\"type\":\"int\"},{\"name\":\"obuMacID\",\"type\":\"int\"},{\"name\":\"obuNum\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"payCardID\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"payCardType\",\"type\":\"int\"},{\"name\":\"iccIssuer\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"cpuCardID\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"vehicleType\",\"type\":\"int\"},{\"name\":\"vehPlate\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"vehColor\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"opTime\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"direction\",\"type\":\"int\"},{\"name\":\"vehStatus\",\"type\":\"int\"},{\"name\":\"spare1\",\"type\":\"int\"},{\"name\":\"spare2\",\"type\":\"int\"},{\"name\":\"spare3\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"spare4\",\"type\":[\"string\",\"null\"],\"default\":\"null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ETCPassListAvro> ENCODER =
      new BinaryMessageEncoder<ETCPassListAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ETCPassListAvro> DECODER =
      new BinaryMessageDecoder<ETCPassListAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ETCPassListAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ETCPassListAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ETCPassListAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ETCPassListAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ETCPassListAvro from a ByteBuffer. */
  public static ETCPassListAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int recordNo;
  @Deprecated public java.lang.CharSequence serialNo;
  @Deprecated public int flagNetRoadID;
  @Deprecated public int flagRoadID;
  @Deprecated public int flagID;
  @Deprecated public int obuType;
  @Deprecated public int obuMacID;
  @Deprecated public java.lang.CharSequence obuNum;
  @Deprecated public java.lang.CharSequence payCardID;
  @Deprecated public int payCardType;
  @Deprecated public java.lang.CharSequence iccIssuer;
  @Deprecated public java.lang.CharSequence cpuCardID;
  @Deprecated public int vehicleType;
  @Deprecated public java.lang.CharSequence vehPlate;
  @Deprecated public java.lang.CharSequence vehColor;
  @Deprecated public java.lang.CharSequence opTime;
  @Deprecated public int direction;
  @Deprecated public int vehStatus;
  @Deprecated public int spare1;
  @Deprecated public int spare2;
  @Deprecated public java.lang.CharSequence spare3;
  @Deprecated public java.lang.CharSequence spare4;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ETCPassListAvro() {}

  /**
   * All-args constructor.
   * @param recordNo The new value for recordNo
   * @param serialNo The new value for serialNo
   * @param flagNetRoadID The new value for flagNetRoadID
   * @param flagRoadID The new value for flagRoadID
   * @param flagID The new value for flagID
   * @param obuType The new value for obuType
   * @param obuMacID The new value for obuMacID
   * @param obuNum The new value for obuNum
   * @param payCardID The new value for payCardID
   * @param payCardType The new value for payCardType
   * @param iccIssuer The new value for iccIssuer
   * @param cpuCardID The new value for cpuCardID
   * @param vehicleType The new value for vehicleType
   * @param vehPlate The new value for vehPlate
   * @param vehColor The new value for vehColor
   * @param opTime The new value for opTime
   * @param direction The new value for direction
   * @param vehStatus The new value for vehStatus
   * @param spare1 The new value for spare1
   * @param spare2 The new value for spare2
   * @param spare3 The new value for spare3
   * @param spare4 The new value for spare4
   */
  public ETCPassListAvro(java.lang.Integer recordNo, java.lang.CharSequence serialNo, java.lang.Integer flagNetRoadID, java.lang.Integer flagRoadID, java.lang.Integer flagID, java.lang.Integer obuType, java.lang.Integer obuMacID, java.lang.CharSequence obuNum, java.lang.CharSequence payCardID, java.lang.Integer payCardType, java.lang.CharSequence iccIssuer, java.lang.CharSequence cpuCardID, java.lang.Integer vehicleType, java.lang.CharSequence vehPlate, java.lang.CharSequence vehColor, java.lang.CharSequence opTime, java.lang.Integer direction, java.lang.Integer vehStatus, java.lang.Integer spare1, java.lang.Integer spare2, java.lang.CharSequence spare3, java.lang.CharSequence spare4) {
    this.recordNo = recordNo;
    this.serialNo = serialNo;
    this.flagNetRoadID = flagNetRoadID;
    this.flagRoadID = flagRoadID;
    this.flagID = flagID;
    this.obuType = obuType;
    this.obuMacID = obuMacID;
    this.obuNum = obuNum;
    this.payCardID = payCardID;
    this.payCardType = payCardType;
    this.iccIssuer = iccIssuer;
    this.cpuCardID = cpuCardID;
    this.vehicleType = vehicleType;
    this.vehPlate = vehPlate;
    this.vehColor = vehColor;
    this.opTime = opTime;
    this.direction = direction;
    this.vehStatus = vehStatus;
    this.spare1 = spare1;
    this.spare2 = spare2;
    this.spare3 = spare3;
    this.spare4 = spare4;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return recordNo;
    case 1: return serialNo;
    case 2: return flagNetRoadID;
    case 3: return flagRoadID;
    case 4: return flagID;
    case 5: return obuType;
    case 6: return obuMacID;
    case 7: return obuNum;
    case 8: return payCardID;
    case 9: return payCardType;
    case 10: return iccIssuer;
    case 11: return cpuCardID;
    case 12: return vehicleType;
    case 13: return vehPlate;
    case 14: return vehColor;
    case 15: return opTime;
    case 16: return direction;
    case 17: return vehStatus;
    case 18: return spare1;
    case 19: return spare2;
    case 20: return spare3;
    case 21: return spare4;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: recordNo = (java.lang.Integer)value$; break;
    case 1: serialNo = (java.lang.CharSequence)value$; break;
    case 2: flagNetRoadID = (java.lang.Integer)value$; break;
    case 3: flagRoadID = (java.lang.Integer)value$; break;
    case 4: flagID = (java.lang.Integer)value$; break;
    case 5: obuType = (java.lang.Integer)value$; break;
    case 6: obuMacID = (java.lang.Integer)value$; break;
    case 7: obuNum = (java.lang.CharSequence)value$; break;
    case 8: payCardID = (java.lang.CharSequence)value$; break;
    case 9: payCardType = (java.lang.Integer)value$; break;
    case 10: iccIssuer = (java.lang.CharSequence)value$; break;
    case 11: cpuCardID = (java.lang.CharSequence)value$; break;
    case 12: vehicleType = (java.lang.Integer)value$; break;
    case 13: vehPlate = (java.lang.CharSequence)value$; break;
    case 14: vehColor = (java.lang.CharSequence)value$; break;
    case 15: opTime = (java.lang.CharSequence)value$; break;
    case 16: direction = (java.lang.Integer)value$; break;
    case 17: vehStatus = (java.lang.Integer)value$; break;
    case 18: spare1 = (java.lang.Integer)value$; break;
    case 19: spare2 = (java.lang.Integer)value$; break;
    case 20: spare3 = (java.lang.CharSequence)value$; break;
    case 21: spare4 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'recordNo' field.
   * @return The value of the 'recordNo' field.
   */
  public java.lang.Integer getRecordNo() {
    return recordNo;
  }

  /**
   * Sets the value of the 'recordNo' field.
   * @param value the value to set.
   */
  public void setRecordNo(java.lang.Integer value) {
    this.recordNo = value;
  }

  /**
   * Gets the value of the 'serialNo' field.
   * @return The value of the 'serialNo' field.
   */
  public java.lang.CharSequence getSerialNo() {
    return serialNo;
  }

  /**
   * Sets the value of the 'serialNo' field.
   * @param value the value to set.
   */
  public void setSerialNo(java.lang.CharSequence value) {
    this.serialNo = value;
  }

  /**
   * Gets the value of the 'flagNetRoadID' field.
   * @return The value of the 'flagNetRoadID' field.
   */
  public java.lang.Integer getFlagNetRoadID() {
    return flagNetRoadID;
  }

  /**
   * Sets the value of the 'flagNetRoadID' field.
   * @param value the value to set.
   */
  public void setFlagNetRoadID(java.lang.Integer value) {
    this.flagNetRoadID = value;
  }

  /**
   * Gets the value of the 'flagRoadID' field.
   * @return The value of the 'flagRoadID' field.
   */
  public java.lang.Integer getFlagRoadID() {
    return flagRoadID;
  }

  /**
   * Sets the value of the 'flagRoadID' field.
   * @param value the value to set.
   */
  public void setFlagRoadID(java.lang.Integer value) {
    this.flagRoadID = value;
  }

  /**
   * Gets the value of the 'flagID' field.
   * @return The value of the 'flagID' field.
   */
  public java.lang.Integer getFlagID() {
    return flagID;
  }

  /**
   * Sets the value of the 'flagID' field.
   * @param value the value to set.
   */
  public void setFlagID(java.lang.Integer value) {
    this.flagID = value;
  }

  /**
   * Gets the value of the 'obuType' field.
   * @return The value of the 'obuType' field.
   */
  public java.lang.Integer getObuType() {
    return obuType;
  }

  /**
   * Sets the value of the 'obuType' field.
   * @param value the value to set.
   */
  public void setObuType(java.lang.Integer value) {
    this.obuType = value;
  }

  /**
   * Gets the value of the 'obuMacID' field.
   * @return The value of the 'obuMacID' field.
   */
  public java.lang.Integer getObuMacID() {
    return obuMacID;
  }

  /**
   * Sets the value of the 'obuMacID' field.
   * @param value the value to set.
   */
  public void setObuMacID(java.lang.Integer value) {
    this.obuMacID = value;
  }

  /**
   * Gets the value of the 'obuNum' field.
   * @return The value of the 'obuNum' field.
   */
  public java.lang.CharSequence getObuNum() {
    return obuNum;
  }

  /**
   * Sets the value of the 'obuNum' field.
   * @param value the value to set.
   */
  public void setObuNum(java.lang.CharSequence value) {
    this.obuNum = value;
  }

  /**
   * Gets the value of the 'payCardID' field.
   * @return The value of the 'payCardID' field.
   */
  public java.lang.CharSequence getPayCardID() {
    return payCardID;
  }

  /**
   * Sets the value of the 'payCardID' field.
   * @param value the value to set.
   */
  public void setPayCardID(java.lang.CharSequence value) {
    this.payCardID = value;
  }

  /**
   * Gets the value of the 'payCardType' field.
   * @return The value of the 'payCardType' field.
   */
  public java.lang.Integer getPayCardType() {
    return payCardType;
  }

  /**
   * Sets the value of the 'payCardType' field.
   * @param value the value to set.
   */
  public void setPayCardType(java.lang.Integer value) {
    this.payCardType = value;
  }

  /**
   * Gets the value of the 'iccIssuer' field.
   * @return The value of the 'iccIssuer' field.
   */
  public java.lang.CharSequence getIccIssuer() {
    return iccIssuer;
  }

  /**
   * Sets the value of the 'iccIssuer' field.
   * @param value the value to set.
   */
  public void setIccIssuer(java.lang.CharSequence value) {
    this.iccIssuer = value;
  }

  /**
   * Gets the value of the 'cpuCardID' field.
   * @return The value of the 'cpuCardID' field.
   */
  public java.lang.CharSequence getCpuCardID() {
    return cpuCardID;
  }

  /**
   * Sets the value of the 'cpuCardID' field.
   * @param value the value to set.
   */
  public void setCpuCardID(java.lang.CharSequence value) {
    this.cpuCardID = value;
  }

  /**
   * Gets the value of the 'vehicleType' field.
   * @return The value of the 'vehicleType' field.
   */
  public java.lang.Integer getVehicleType() {
    return vehicleType;
  }

  /**
   * Sets the value of the 'vehicleType' field.
   * @param value the value to set.
   */
  public void setVehicleType(java.lang.Integer value) {
    this.vehicleType = value;
  }

  /**
   * Gets the value of the 'vehPlate' field.
   * @return The value of the 'vehPlate' field.
   */
  public java.lang.CharSequence getVehPlate() {
    return vehPlate;
  }

  /**
   * Sets the value of the 'vehPlate' field.
   * @param value the value to set.
   */
  public void setVehPlate(java.lang.CharSequence value) {
    this.vehPlate = value;
  }

  /**
   * Gets the value of the 'vehColor' field.
   * @return The value of the 'vehColor' field.
   */
  public java.lang.CharSequence getVehColor() {
    return vehColor;
  }

  /**
   * Sets the value of the 'vehColor' field.
   * @param value the value to set.
   */
  public void setVehColor(java.lang.CharSequence value) {
    this.vehColor = value;
  }

  /**
   * Gets the value of the 'opTime' field.
   * @return The value of the 'opTime' field.
   */
  public java.lang.CharSequence getOpTime() {
    return opTime;
  }

  /**
   * Sets the value of the 'opTime' field.
   * @param value the value to set.
   */
  public void setOpTime(java.lang.CharSequence value) {
    this.opTime = value;
  }

  /**
   * Gets the value of the 'direction' field.
   * @return The value of the 'direction' field.
   */
  public java.lang.Integer getDirection() {
    return direction;
  }

  /**
   * Sets the value of the 'direction' field.
   * @param value the value to set.
   */
  public void setDirection(java.lang.Integer value) {
    this.direction = value;
  }

  /**
   * Gets the value of the 'vehStatus' field.
   * @return The value of the 'vehStatus' field.
   */
  public java.lang.Integer getVehStatus() {
    return vehStatus;
  }

  /**
   * Sets the value of the 'vehStatus' field.
   * @param value the value to set.
   */
  public void setVehStatus(java.lang.Integer value) {
    this.vehStatus = value;
  }

  /**
   * Gets the value of the 'spare1' field.
   * @return The value of the 'spare1' field.
   */
  public java.lang.Integer getSpare1() {
    return spare1;
  }

  /**
   * Sets the value of the 'spare1' field.
   * @param value the value to set.
   */
  public void setSpare1(java.lang.Integer value) {
    this.spare1 = value;
  }

  /**
   * Gets the value of the 'spare2' field.
   * @return The value of the 'spare2' field.
   */
  public java.lang.Integer getSpare2() {
    return spare2;
  }

  /**
   * Sets the value of the 'spare2' field.
   * @param value the value to set.
   */
  public void setSpare2(java.lang.Integer value) {
    this.spare2 = value;
  }

  /**
   * Gets the value of the 'spare3' field.
   * @return The value of the 'spare3' field.
   */
  public java.lang.CharSequence getSpare3() {
    return spare3;
  }

  /**
   * Sets the value of the 'spare3' field.
   * @param value the value to set.
   */
  public void setSpare3(java.lang.CharSequence value) {
    this.spare3 = value;
  }

  /**
   * Gets the value of the 'spare4' field.
   * @return The value of the 'spare4' field.
   */
  public java.lang.CharSequence getSpare4() {
    return spare4;
  }

  /**
   * Sets the value of the 'spare4' field.
   * @param value the value to set.
   */
  public void setSpare4(java.lang.CharSequence value) {
    this.spare4 = value;
  }

  /**
   * Creates a new ETCPassListAvro RecordBuilder.
   * @return A new ETCPassListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.ETCPassListAvro.Builder newBuilder() {
    return new com.leatop.bee.web.po.ETCPassListAvro.Builder();
  }

  /**
   * Creates a new ETCPassListAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ETCPassListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.ETCPassListAvro.Builder newBuilder(com.leatop.bee.web.po.ETCPassListAvro.Builder other) {
    return new com.leatop.bee.web.po.ETCPassListAvro.Builder(other);
  }

  /**
   * Creates a new ETCPassListAvro RecordBuilder by copying an existing ETCPassListAvro instance.
   * @param other The existing instance to copy.
   * @return A new ETCPassListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.ETCPassListAvro.Builder newBuilder(com.leatop.bee.web.po.ETCPassListAvro other) {
    return new com.leatop.bee.web.po.ETCPassListAvro.Builder(other);
  }

  /**
   * RecordBuilder for ETCPassListAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ETCPassListAvro>
    implements org.apache.avro.data.RecordBuilder<ETCPassListAvro> {

    private int recordNo;
    private java.lang.CharSequence serialNo;
    private int flagNetRoadID;
    private int flagRoadID;
    private int flagID;
    private int obuType;
    private int obuMacID;
    private java.lang.CharSequence obuNum;
    private java.lang.CharSequence payCardID;
    private int payCardType;
    private java.lang.CharSequence iccIssuer;
    private java.lang.CharSequence cpuCardID;
    private int vehicleType;
    private java.lang.CharSequence vehPlate;
    private java.lang.CharSequence vehColor;
    private java.lang.CharSequence opTime;
    private int direction;
    private int vehStatus;
    private int spare1;
    private int spare2;
    private java.lang.CharSequence spare3;
    private java.lang.CharSequence spare4;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.leatop.bee.web.po.ETCPassListAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.recordNo)) {
        this.recordNo = data().deepCopy(fields()[0].schema(), other.recordNo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serialNo)) {
        this.serialNo = data().deepCopy(fields()[1].schema(), other.serialNo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.flagNetRoadID)) {
        this.flagNetRoadID = data().deepCopy(fields()[2].schema(), other.flagNetRoadID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.flagRoadID)) {
        this.flagRoadID = data().deepCopy(fields()[3].schema(), other.flagRoadID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.flagID)) {
        this.flagID = data().deepCopy(fields()[4].schema(), other.flagID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.obuType)) {
        this.obuType = data().deepCopy(fields()[5].schema(), other.obuType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.obuMacID)) {
        this.obuMacID = data().deepCopy(fields()[6].schema(), other.obuMacID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.obuNum)) {
        this.obuNum = data().deepCopy(fields()[7].schema(), other.obuNum);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.payCardID)) {
        this.payCardID = data().deepCopy(fields()[8].schema(), other.payCardID);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.payCardType)) {
        this.payCardType = data().deepCopy(fields()[9].schema(), other.payCardType);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.iccIssuer)) {
        this.iccIssuer = data().deepCopy(fields()[10].schema(), other.iccIssuer);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.cpuCardID)) {
        this.cpuCardID = data().deepCopy(fields()[11].schema(), other.cpuCardID);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.vehicleType)) {
        this.vehicleType = data().deepCopy(fields()[12].schema(), other.vehicleType);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.vehPlate)) {
        this.vehPlate = data().deepCopy(fields()[13].schema(), other.vehPlate);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.vehColor)) {
        this.vehColor = data().deepCopy(fields()[14].schema(), other.vehColor);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.opTime)) {
        this.opTime = data().deepCopy(fields()[15].schema(), other.opTime);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.direction)) {
        this.direction = data().deepCopy(fields()[16].schema(), other.direction);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.vehStatus)) {
        this.vehStatus = data().deepCopy(fields()[17].schema(), other.vehStatus);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.spare1)) {
        this.spare1 = data().deepCopy(fields()[18].schema(), other.spare1);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.spare2)) {
        this.spare2 = data().deepCopy(fields()[19].schema(), other.spare2);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.spare3)) {
        this.spare3 = data().deepCopy(fields()[20].schema(), other.spare3);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.spare4)) {
        this.spare4 = data().deepCopy(fields()[21].schema(), other.spare4);
        fieldSetFlags()[21] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ETCPassListAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.leatop.bee.web.po.ETCPassListAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.recordNo)) {
        this.recordNo = data().deepCopy(fields()[0].schema(), other.recordNo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serialNo)) {
        this.serialNo = data().deepCopy(fields()[1].schema(), other.serialNo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.flagNetRoadID)) {
        this.flagNetRoadID = data().deepCopy(fields()[2].schema(), other.flagNetRoadID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.flagRoadID)) {
        this.flagRoadID = data().deepCopy(fields()[3].schema(), other.flagRoadID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.flagID)) {
        this.flagID = data().deepCopy(fields()[4].schema(), other.flagID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.obuType)) {
        this.obuType = data().deepCopy(fields()[5].schema(), other.obuType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.obuMacID)) {
        this.obuMacID = data().deepCopy(fields()[6].schema(), other.obuMacID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.obuNum)) {
        this.obuNum = data().deepCopy(fields()[7].schema(), other.obuNum);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.payCardID)) {
        this.payCardID = data().deepCopy(fields()[8].schema(), other.payCardID);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.payCardType)) {
        this.payCardType = data().deepCopy(fields()[9].schema(), other.payCardType);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.iccIssuer)) {
        this.iccIssuer = data().deepCopy(fields()[10].schema(), other.iccIssuer);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.cpuCardID)) {
        this.cpuCardID = data().deepCopy(fields()[11].schema(), other.cpuCardID);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.vehicleType)) {
        this.vehicleType = data().deepCopy(fields()[12].schema(), other.vehicleType);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.vehPlate)) {
        this.vehPlate = data().deepCopy(fields()[13].schema(), other.vehPlate);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.vehColor)) {
        this.vehColor = data().deepCopy(fields()[14].schema(), other.vehColor);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.opTime)) {
        this.opTime = data().deepCopy(fields()[15].schema(), other.opTime);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.direction)) {
        this.direction = data().deepCopy(fields()[16].schema(), other.direction);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.vehStatus)) {
        this.vehStatus = data().deepCopy(fields()[17].schema(), other.vehStatus);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.spare1)) {
        this.spare1 = data().deepCopy(fields()[18].schema(), other.spare1);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.spare2)) {
        this.spare2 = data().deepCopy(fields()[19].schema(), other.spare2);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.spare3)) {
        this.spare3 = data().deepCopy(fields()[20].schema(), other.spare3);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.spare4)) {
        this.spare4 = data().deepCopy(fields()[21].schema(), other.spare4);
        fieldSetFlags()[21] = true;
      }
    }

    /**
      * Gets the value of the 'recordNo' field.
      * @return The value.
      */
    public java.lang.Integer getRecordNo() {
      return recordNo;
    }

    /**
      * Sets the value of the 'recordNo' field.
      * @param value The value of 'recordNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setRecordNo(int value) {
      validate(fields()[0], value);
      this.recordNo = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'recordNo' field has been set.
      * @return True if the 'recordNo' field has been set, false otherwise.
      */
    public boolean hasRecordNo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'recordNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearRecordNo() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'serialNo' field.
      * @return The value.
      */
    public java.lang.CharSequence getSerialNo() {
      return serialNo;
    }

    /**
      * Sets the value of the 'serialNo' field.
      * @param value The value of 'serialNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setSerialNo(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.serialNo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'serialNo' field has been set.
      * @return True if the 'serialNo' field has been set, false otherwise.
      */
    public boolean hasSerialNo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'serialNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearSerialNo() {
      serialNo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagNetRoadID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagNetRoadID() {
      return flagNetRoadID;
    }

    /**
      * Sets the value of the 'flagNetRoadID' field.
      * @param value The value of 'flagNetRoadID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setFlagNetRoadID(int value) {
      validate(fields()[2], value);
      this.flagNetRoadID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'flagNetRoadID' field has been set.
      * @return True if the 'flagNetRoadID' field has been set, false otherwise.
      */
    public boolean hasFlagNetRoadID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'flagNetRoadID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearFlagNetRoadID() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagRoadID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagRoadID() {
      return flagRoadID;
    }

    /**
      * Sets the value of the 'flagRoadID' field.
      * @param value The value of 'flagRoadID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setFlagRoadID(int value) {
      validate(fields()[3], value);
      this.flagRoadID = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'flagRoadID' field has been set.
      * @return True if the 'flagRoadID' field has been set, false otherwise.
      */
    public boolean hasFlagRoadID() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'flagRoadID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearFlagRoadID() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagID() {
      return flagID;
    }

    /**
      * Sets the value of the 'flagID' field.
      * @param value The value of 'flagID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setFlagID(int value) {
      validate(fields()[4], value);
      this.flagID = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'flagID' field has been set.
      * @return True if the 'flagID' field has been set, false otherwise.
      */
    public boolean hasFlagID() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'flagID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearFlagID() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'obuType' field.
      * @return The value.
      */
    public java.lang.Integer getObuType() {
      return obuType;
    }

    /**
      * Sets the value of the 'obuType' field.
      * @param value The value of 'obuType'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setObuType(int value) {
      validate(fields()[5], value);
      this.obuType = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'obuType' field has been set.
      * @return True if the 'obuType' field has been set, false otherwise.
      */
    public boolean hasObuType() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'obuType' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearObuType() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'obuMacID' field.
      * @return The value.
      */
    public java.lang.Integer getObuMacID() {
      return obuMacID;
    }

    /**
      * Sets the value of the 'obuMacID' field.
      * @param value The value of 'obuMacID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setObuMacID(int value) {
      validate(fields()[6], value);
      this.obuMacID = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'obuMacID' field has been set.
      * @return True if the 'obuMacID' field has been set, false otherwise.
      */
    public boolean hasObuMacID() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'obuMacID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearObuMacID() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'obuNum' field.
      * @return The value.
      */
    public java.lang.CharSequence getObuNum() {
      return obuNum;
    }

    /**
      * Sets the value of the 'obuNum' field.
      * @param value The value of 'obuNum'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setObuNum(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.obuNum = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'obuNum' field has been set.
      * @return True if the 'obuNum' field has been set, false otherwise.
      */
    public boolean hasObuNum() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'obuNum' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearObuNum() {
      obuNum = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'payCardID' field.
      * @return The value.
      */
    public java.lang.CharSequence getPayCardID() {
      return payCardID;
    }

    /**
      * Sets the value of the 'payCardID' field.
      * @param value The value of 'payCardID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setPayCardID(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.payCardID = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'payCardID' field has been set.
      * @return True if the 'payCardID' field has been set, false otherwise.
      */
    public boolean hasPayCardID() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'payCardID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearPayCardID() {
      payCardID = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'payCardType' field.
      * @return The value.
      */
    public java.lang.Integer getPayCardType() {
      return payCardType;
    }

    /**
      * Sets the value of the 'payCardType' field.
      * @param value The value of 'payCardType'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setPayCardType(int value) {
      validate(fields()[9], value);
      this.payCardType = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'payCardType' field has been set.
      * @return True if the 'payCardType' field has been set, false otherwise.
      */
    public boolean hasPayCardType() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'payCardType' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearPayCardType() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'iccIssuer' field.
      * @return The value.
      */
    public java.lang.CharSequence getIccIssuer() {
      return iccIssuer;
    }

    /**
      * Sets the value of the 'iccIssuer' field.
      * @param value The value of 'iccIssuer'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setIccIssuer(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.iccIssuer = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'iccIssuer' field has been set.
      * @return True if the 'iccIssuer' field has been set, false otherwise.
      */
    public boolean hasIccIssuer() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'iccIssuer' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearIccIssuer() {
      iccIssuer = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'cpuCardID' field.
      * @return The value.
      */
    public java.lang.CharSequence getCpuCardID() {
      return cpuCardID;
    }

    /**
      * Sets the value of the 'cpuCardID' field.
      * @param value The value of 'cpuCardID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setCpuCardID(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.cpuCardID = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'cpuCardID' field has been set.
      * @return True if the 'cpuCardID' field has been set, false otherwise.
      */
    public boolean hasCpuCardID() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'cpuCardID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearCpuCardID() {
      cpuCardID = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehicleType' field.
      * @return The value.
      */
    public java.lang.Integer getVehicleType() {
      return vehicleType;
    }

    /**
      * Sets the value of the 'vehicleType' field.
      * @param value The value of 'vehicleType'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setVehicleType(int value) {
      validate(fields()[12], value);
      this.vehicleType = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'vehicleType' field has been set.
      * @return True if the 'vehicleType' field has been set, false otherwise.
      */
    public boolean hasVehicleType() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'vehicleType' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearVehicleType() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehPlate' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehPlate() {
      return vehPlate;
    }

    /**
      * Sets the value of the 'vehPlate' field.
      * @param value The value of 'vehPlate'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setVehPlate(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.vehPlate = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'vehPlate' field has been set.
      * @return True if the 'vehPlate' field has been set, false otherwise.
      */
    public boolean hasVehPlate() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'vehPlate' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearVehPlate() {
      vehPlate = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehColor' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehColor() {
      return vehColor;
    }

    /**
      * Sets the value of the 'vehColor' field.
      * @param value The value of 'vehColor'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setVehColor(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.vehColor = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'vehColor' field has been set.
      * @return True if the 'vehColor' field has been set, false otherwise.
      */
    public boolean hasVehColor() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'vehColor' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearVehColor() {
      vehColor = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'opTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getOpTime() {
      return opTime;
    }

    /**
      * Sets the value of the 'opTime' field.
      * @param value The value of 'opTime'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setOpTime(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.opTime = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'opTime' field has been set.
      * @return True if the 'opTime' field has been set, false otherwise.
      */
    public boolean hasOpTime() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'opTime' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearOpTime() {
      opTime = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'direction' field.
      * @return The value.
      */
    public java.lang.Integer getDirection() {
      return direction;
    }

    /**
      * Sets the value of the 'direction' field.
      * @param value The value of 'direction'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setDirection(int value) {
      validate(fields()[16], value);
      this.direction = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'direction' field has been set.
      * @return True if the 'direction' field has been set, false otherwise.
      */
    public boolean hasDirection() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'direction' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearDirection() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehStatus' field.
      * @return The value.
      */
    public java.lang.Integer getVehStatus() {
      return vehStatus;
    }

    /**
      * Sets the value of the 'vehStatus' field.
      * @param value The value of 'vehStatus'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setVehStatus(int value) {
      validate(fields()[17], value);
      this.vehStatus = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'vehStatus' field has been set.
      * @return True if the 'vehStatus' field has been set, false otherwise.
      */
    public boolean hasVehStatus() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'vehStatus' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearVehStatus() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'spare1' field.
      * @return The value.
      */
    public java.lang.Integer getSpare1() {
      return spare1;
    }

    /**
      * Sets the value of the 'spare1' field.
      * @param value The value of 'spare1'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setSpare1(int value) {
      validate(fields()[18], value);
      this.spare1 = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'spare1' field has been set.
      * @return True if the 'spare1' field has been set, false otherwise.
      */
    public boolean hasSpare1() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'spare1' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearSpare1() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'spare2' field.
      * @return The value.
      */
    public java.lang.Integer getSpare2() {
      return spare2;
    }

    /**
      * Sets the value of the 'spare2' field.
      * @param value The value of 'spare2'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setSpare2(int value) {
      validate(fields()[19], value);
      this.spare2 = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'spare2' field has been set.
      * @return True if the 'spare2' field has been set, false otherwise.
      */
    public boolean hasSpare2() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'spare2' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearSpare2() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'spare3' field.
      * @return The value.
      */
    public java.lang.CharSequence getSpare3() {
      return spare3;
    }

    /**
      * Sets the value of the 'spare3' field.
      * @param value The value of 'spare3'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setSpare3(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.spare3 = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'spare3' field has been set.
      * @return True if the 'spare3' field has been set, false otherwise.
      */
    public boolean hasSpare3() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'spare3' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearSpare3() {
      spare3 = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'spare4' field.
      * @return The value.
      */
    public java.lang.CharSequence getSpare4() {
      return spare4;
    }

    /**
      * Sets the value of the 'spare4' field.
      * @param value The value of 'spare4'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder setSpare4(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.spare4 = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'spare4' field has been set.
      * @return True if the 'spare4' field has been set, false otherwise.
      */
    public boolean hasSpare4() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'spare4' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ETCPassListAvro.Builder clearSpare4() {
      spare4 = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ETCPassListAvro build() {
      try {
        ETCPassListAvro record = new ETCPassListAvro();
        record.recordNo = fieldSetFlags()[0] ? this.recordNo : (java.lang.Integer) defaultValue(fields()[0]);
        record.serialNo = fieldSetFlags()[1] ? this.serialNo : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.flagNetRoadID = fieldSetFlags()[2] ? this.flagNetRoadID : (java.lang.Integer) defaultValue(fields()[2]);
        record.flagRoadID = fieldSetFlags()[3] ? this.flagRoadID : (java.lang.Integer) defaultValue(fields()[3]);
        record.flagID = fieldSetFlags()[4] ? this.flagID : (java.lang.Integer) defaultValue(fields()[4]);
        record.obuType = fieldSetFlags()[5] ? this.obuType : (java.lang.Integer) defaultValue(fields()[5]);
        record.obuMacID = fieldSetFlags()[6] ? this.obuMacID : (java.lang.Integer) defaultValue(fields()[6]);
        record.obuNum = fieldSetFlags()[7] ? this.obuNum : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.payCardID = fieldSetFlags()[8] ? this.payCardID : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.payCardType = fieldSetFlags()[9] ? this.payCardType : (java.lang.Integer) defaultValue(fields()[9]);
        record.iccIssuer = fieldSetFlags()[10] ? this.iccIssuer : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.cpuCardID = fieldSetFlags()[11] ? this.cpuCardID : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.vehicleType = fieldSetFlags()[12] ? this.vehicleType : (java.lang.Integer) defaultValue(fields()[12]);
        record.vehPlate = fieldSetFlags()[13] ? this.vehPlate : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.vehColor = fieldSetFlags()[14] ? this.vehColor : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.opTime = fieldSetFlags()[15] ? this.opTime : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.direction = fieldSetFlags()[16] ? this.direction : (java.lang.Integer) defaultValue(fields()[16]);
        record.vehStatus = fieldSetFlags()[17] ? this.vehStatus : (java.lang.Integer) defaultValue(fields()[17]);
        record.spare1 = fieldSetFlags()[18] ? this.spare1 : (java.lang.Integer) defaultValue(fields()[18]);
        record.spare2 = fieldSetFlags()[19] ? this.spare2 : (java.lang.Integer) defaultValue(fields()[19]);
        record.spare3 = fieldSetFlags()[20] ? this.spare3 : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.spare4 = fieldSetFlags()[21] ? this.spare4 : (java.lang.CharSequence) defaultValue(fields()[21]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ETCPassListAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<ETCPassListAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ETCPassListAvro>
    READER$ = (org.apache.avro.io.DatumReader<ETCPassListAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
