/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leatop.bee.web.po;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FlagEtcPassListAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7482788748838916157L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FlagEtcPassListAvro\",\"namespace\":\"com.leatop.bee.web.po\",\"fields\":[{\"name\":\"recordNo\",\"type\":\"int\"},{\"name\":\"serialNo\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"flagNetRoadID\",\"type\":\"int\"},{\"name\":\"flagRoadID\",\"type\":\"int\"},{\"name\":\"flagID\",\"type\":\"int\"},{\"name\":\"posId\",\"type\":\"int\"},{\"name\":\"laneNo\",\"type\":\"int\"},{\"name\":\"obuType\",\"type\":\"int\"},{\"name\":\"obuMacID\",\"type\":\"int\"},{\"name\":\"obuNum\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"etcTermCode\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"enRoadNo\",\"type\":\"int\"},{\"name\":\"enStationNo\",\"type\":\"int\"},{\"name\":\"enTime\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"cpuCardID\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"vehicleType\",\"type\":\"int\"},{\"name\":\"tollAmount\",\"type\":\"int\"},{\"name\":\"discountFee\",\"type\":\"int\"},{\"name\":\"vehPlate\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"vehColor\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"opTime\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"direction\",\"type\":\"int\"},{\"name\":\"vehStatus\",\"type\":\"int\"},{\"name\":\"obuElectrical\",\"type\":\"int\"},{\"name\":\"eevStatus\",\"type\":\"int\"},{\"name\":\"picSerialNo\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"spare1\",\"type\":\"int\"},{\"name\":\"spare2\",\"type\":\"int\"},{\"name\":\"spare3\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"spare4\",\"type\":[\"string\",\"null\"],\"default\":\"null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FlagEtcPassListAvro> ENCODER =
      new BinaryMessageEncoder<FlagEtcPassListAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FlagEtcPassListAvro> DECODER =
      new BinaryMessageDecoder<FlagEtcPassListAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FlagEtcPassListAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FlagEtcPassListAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FlagEtcPassListAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FlagEtcPassListAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FlagEtcPassListAvro from a ByteBuffer. */
  public static FlagEtcPassListAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int recordNo;
  @Deprecated public java.lang.CharSequence serialNo;
  @Deprecated public int flagNetRoadID;
  @Deprecated public int flagRoadID;
  @Deprecated public int flagID;
  @Deprecated public int posId;
  @Deprecated public int laneNo;
  @Deprecated public int obuType;
  @Deprecated public int obuMacID;
  @Deprecated public java.lang.CharSequence obuNum;
  @Deprecated public java.lang.CharSequence etcTermCode;
  @Deprecated public int enRoadNo;
  @Deprecated public int enStationNo;
  @Deprecated public java.lang.CharSequence enTime;
  @Deprecated public java.lang.CharSequence cpuCardID;
  @Deprecated public int vehicleType;
  @Deprecated public int tollAmount;
  @Deprecated public int discountFee;
  @Deprecated public java.lang.CharSequence vehPlate;
  @Deprecated public java.lang.CharSequence vehColor;
  @Deprecated public java.lang.CharSequence opTime;
  @Deprecated public int direction;
  @Deprecated public int vehStatus;
  @Deprecated public int obuElectrical;
  @Deprecated public int eevStatus;
  @Deprecated public java.lang.CharSequence picSerialNo;
  @Deprecated public int spare1;
  @Deprecated public int spare2;
  @Deprecated public java.lang.CharSequence spare3;
  @Deprecated public java.lang.CharSequence spare4;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FlagEtcPassListAvro() {}

  /**
   * All-args constructor.
   * @param recordNo The new value for recordNo
   * @param serialNo The new value for serialNo
   * @param flagNetRoadID The new value for flagNetRoadID
   * @param flagRoadID The new value for flagRoadID
   * @param flagID The new value for flagID
   * @param posId The new value for posId
   * @param laneNo The new value for laneNo
   * @param obuType The new value for obuType
   * @param obuMacID The new value for obuMacID
   * @param obuNum The new value for obuNum
   * @param etcTermCode The new value for etcTermCode
   * @param enRoadNo The new value for enRoadNo
   * @param enStationNo The new value for enStationNo
   * @param enTime The new value for enTime
   * @param cpuCardID The new value for cpuCardID
   * @param vehicleType The new value for vehicleType
   * @param tollAmount The new value for tollAmount
   * @param discountFee The new value for discountFee
   * @param vehPlate The new value for vehPlate
   * @param vehColor The new value for vehColor
   * @param opTime The new value for opTime
   * @param direction The new value for direction
   * @param vehStatus The new value for vehStatus
   * @param obuElectrical The new value for obuElectrical
   * @param eevStatus The new value for eevStatus
   * @param picSerialNo The new value for picSerialNo
   * @param spare1 The new value for spare1
   * @param spare2 The new value for spare2
   * @param spare3 The new value for spare3
   * @param spare4 The new value for spare4
   */
  public FlagEtcPassListAvro(java.lang.Integer recordNo, java.lang.CharSequence serialNo, java.lang.Integer flagNetRoadID, java.lang.Integer flagRoadID, java.lang.Integer flagID, java.lang.Integer posId, java.lang.Integer laneNo, java.lang.Integer obuType, java.lang.Integer obuMacID, java.lang.CharSequence obuNum, java.lang.CharSequence etcTermCode, java.lang.Integer enRoadNo, java.lang.Integer enStationNo, java.lang.CharSequence enTime, java.lang.CharSequence cpuCardID, java.lang.Integer vehicleType, java.lang.Integer tollAmount, java.lang.Integer discountFee, java.lang.CharSequence vehPlate, java.lang.CharSequence vehColor, java.lang.CharSequence opTime, java.lang.Integer direction, java.lang.Integer vehStatus, java.lang.Integer obuElectrical, java.lang.Integer eevStatus, java.lang.CharSequence picSerialNo, java.lang.Integer spare1, java.lang.Integer spare2, java.lang.CharSequence spare3, java.lang.CharSequence spare4) {
    this.recordNo = recordNo;
    this.serialNo = serialNo;
    this.flagNetRoadID = flagNetRoadID;
    this.flagRoadID = flagRoadID;
    this.flagID = flagID;
    this.posId = posId;
    this.laneNo = laneNo;
    this.obuType = obuType;
    this.obuMacID = obuMacID;
    this.obuNum = obuNum;
    this.etcTermCode = etcTermCode;
    this.enRoadNo = enRoadNo;
    this.enStationNo = enStationNo;
    this.enTime = enTime;
    this.cpuCardID = cpuCardID;
    this.vehicleType = vehicleType;
    this.tollAmount = tollAmount;
    this.discountFee = discountFee;
    this.vehPlate = vehPlate;
    this.vehColor = vehColor;
    this.opTime = opTime;
    this.direction = direction;
    this.vehStatus = vehStatus;
    this.obuElectrical = obuElectrical;
    this.eevStatus = eevStatus;
    this.picSerialNo = picSerialNo;
    this.spare1 = spare1;
    this.spare2 = spare2;
    this.spare3 = spare3;
    this.spare4 = spare4;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return recordNo;
    case 1: return serialNo;
    case 2: return flagNetRoadID;
    case 3: return flagRoadID;
    case 4: return flagID;
    case 5: return posId;
    case 6: return laneNo;
    case 7: return obuType;
    case 8: return obuMacID;
    case 9: return obuNum;
    case 10: return etcTermCode;
    case 11: return enRoadNo;
    case 12: return enStationNo;
    case 13: return enTime;
    case 14: return cpuCardID;
    case 15: return vehicleType;
    case 16: return tollAmount;
    case 17: return discountFee;
    case 18: return vehPlate;
    case 19: return vehColor;
    case 20: return opTime;
    case 21: return direction;
    case 22: return vehStatus;
    case 23: return obuElectrical;
    case 24: return eevStatus;
    case 25: return picSerialNo;
    case 26: return spare1;
    case 27: return spare2;
    case 28: return spare3;
    case 29: return spare4;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: recordNo = (java.lang.Integer)value$; break;
    case 1: serialNo = (java.lang.CharSequence)value$; break;
    case 2: flagNetRoadID = (java.lang.Integer)value$; break;
    case 3: flagRoadID = (java.lang.Integer)value$; break;
    case 4: flagID = (java.lang.Integer)value$; break;
    case 5: posId = (java.lang.Integer)value$; break;
    case 6: laneNo = (java.lang.Integer)value$; break;
    case 7: obuType = (java.lang.Integer)value$; break;
    case 8: obuMacID = (java.lang.Integer)value$; break;
    case 9: obuNum = (java.lang.CharSequence)value$; break;
    case 10: etcTermCode = (java.lang.CharSequence)value$; break;
    case 11: enRoadNo = (java.lang.Integer)value$; break;
    case 12: enStationNo = (java.lang.Integer)value$; break;
    case 13: enTime = (java.lang.CharSequence)value$; break;
    case 14: cpuCardID = (java.lang.CharSequence)value$; break;
    case 15: vehicleType = (java.lang.Integer)value$; break;
    case 16: tollAmount = (java.lang.Integer)value$; break;
    case 17: discountFee = (java.lang.Integer)value$; break;
    case 18: vehPlate = (java.lang.CharSequence)value$; break;
    case 19: vehColor = (java.lang.CharSequence)value$; break;
    case 20: opTime = (java.lang.CharSequence)value$; break;
    case 21: direction = (java.lang.Integer)value$; break;
    case 22: vehStatus = (java.lang.Integer)value$; break;
    case 23: obuElectrical = (java.lang.Integer)value$; break;
    case 24: eevStatus = (java.lang.Integer)value$; break;
    case 25: picSerialNo = (java.lang.CharSequence)value$; break;
    case 26: spare1 = (java.lang.Integer)value$; break;
    case 27: spare2 = (java.lang.Integer)value$; break;
    case 28: spare3 = (java.lang.CharSequence)value$; break;
    case 29: spare4 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'recordNo' field.
   * @return The value of the 'recordNo' field.
   */
  public java.lang.Integer getRecordNo() {
    return recordNo;
  }

  /**
   * Sets the value of the 'recordNo' field.
   * @param value the value to set.
   */
  public void setRecordNo(java.lang.Integer value) {
    this.recordNo = value;
  }

  /**
   * Gets the value of the 'serialNo' field.
   * @return The value of the 'serialNo' field.
   */
  public java.lang.CharSequence getSerialNo() {
    return serialNo;
  }

  /**
   * Sets the value of the 'serialNo' field.
   * @param value the value to set.
   */
  public void setSerialNo(java.lang.CharSequence value) {
    this.serialNo = value;
  }

  /**
   * Gets the value of the 'flagNetRoadID' field.
   * @return The value of the 'flagNetRoadID' field.
   */
  public java.lang.Integer getFlagNetRoadID() {
    return flagNetRoadID;
  }

  /**
   * Sets the value of the 'flagNetRoadID' field.
   * @param value the value to set.
   */
  public void setFlagNetRoadID(java.lang.Integer value) {
    this.flagNetRoadID = value;
  }

  /**
   * Gets the value of the 'flagRoadID' field.
   * @return The value of the 'flagRoadID' field.
   */
  public java.lang.Integer getFlagRoadID() {
    return flagRoadID;
  }

  /**
   * Sets the value of the 'flagRoadID' field.
   * @param value the value to set.
   */
  public void setFlagRoadID(java.lang.Integer value) {
    this.flagRoadID = value;
  }

  /**
   * Gets the value of the 'flagID' field.
   * @return The value of the 'flagID' field.
   */
  public java.lang.Integer getFlagID() {
    return flagID;
  }

  /**
   * Sets the value of the 'flagID' field.
   * @param value the value to set.
   */
  public void setFlagID(java.lang.Integer value) {
    this.flagID = value;
  }

  /**
   * Gets the value of the 'posId' field.
   * @return The value of the 'posId' field.
   */
  public java.lang.Integer getPosId() {
    return posId;
  }

  /**
   * Sets the value of the 'posId' field.
   * @param value the value to set.
   */
  public void setPosId(java.lang.Integer value) {
    this.posId = value;
  }

  /**
   * Gets the value of the 'laneNo' field.
   * @return The value of the 'laneNo' field.
   */
  public java.lang.Integer getLaneNo() {
    return laneNo;
  }

  /**
   * Sets the value of the 'laneNo' field.
   * @param value the value to set.
   */
  public void setLaneNo(java.lang.Integer value) {
    this.laneNo = value;
  }

  /**
   * Gets the value of the 'obuType' field.
   * @return The value of the 'obuType' field.
   */
  public java.lang.Integer getObuType() {
    return obuType;
  }

  /**
   * Sets the value of the 'obuType' field.
   * @param value the value to set.
   */
  public void setObuType(java.lang.Integer value) {
    this.obuType = value;
  }

  /**
   * Gets the value of the 'obuMacID' field.
   * @return The value of the 'obuMacID' field.
   */
  public java.lang.Integer getObuMacID() {
    return obuMacID;
  }

  /**
   * Sets the value of the 'obuMacID' field.
   * @param value the value to set.
   */
  public void setObuMacID(java.lang.Integer value) {
    this.obuMacID = value;
  }

  /**
   * Gets the value of the 'obuNum' field.
   * @return The value of the 'obuNum' field.
   */
  public java.lang.CharSequence getObuNum() {
    return obuNum;
  }

  /**
   * Sets the value of the 'obuNum' field.
   * @param value the value to set.
   */
  public void setObuNum(java.lang.CharSequence value) {
    this.obuNum = value;
  }

  /**
   * Gets the value of the 'etcTermCode' field.
   * @return The value of the 'etcTermCode' field.
   */
  public java.lang.CharSequence getEtcTermCode() {
    return etcTermCode;
  }

  /**
   * Sets the value of the 'etcTermCode' field.
   * @param value the value to set.
   */
  public void setEtcTermCode(java.lang.CharSequence value) {
    this.etcTermCode = value;
  }

  /**
   * Gets the value of the 'enRoadNo' field.
   * @return The value of the 'enRoadNo' field.
   */
  public java.lang.Integer getEnRoadNo() {
    return enRoadNo;
  }

  /**
   * Sets the value of the 'enRoadNo' field.
   * @param value the value to set.
   */
  public void setEnRoadNo(java.lang.Integer value) {
    this.enRoadNo = value;
  }

  /**
   * Gets the value of the 'enStationNo' field.
   * @return The value of the 'enStationNo' field.
   */
  public java.lang.Integer getEnStationNo() {
    return enStationNo;
  }

  /**
   * Sets the value of the 'enStationNo' field.
   * @param value the value to set.
   */
  public void setEnStationNo(java.lang.Integer value) {
    this.enStationNo = value;
  }

  /**
   * Gets the value of the 'enTime' field.
   * @return The value of the 'enTime' field.
   */
  public java.lang.CharSequence getEnTime() {
    return enTime;
  }

  /**
   * Sets the value of the 'enTime' field.
   * @param value the value to set.
   */
  public void setEnTime(java.lang.CharSequence value) {
    this.enTime = value;
  }

  /**
   * Gets the value of the 'cpuCardID' field.
   * @return The value of the 'cpuCardID' field.
   */
  public java.lang.CharSequence getCpuCardID() {
    return cpuCardID;
  }

  /**
   * Sets the value of the 'cpuCardID' field.
   * @param value the value to set.
   */
  public void setCpuCardID(java.lang.CharSequence value) {
    this.cpuCardID = value;
  }

  /**
   * Gets the value of the 'vehicleType' field.
   * @return The value of the 'vehicleType' field.
   */
  public java.lang.Integer getVehicleType() {
    return vehicleType;
  }

  /**
   * Sets the value of the 'vehicleType' field.
   * @param value the value to set.
   */
  public void setVehicleType(java.lang.Integer value) {
    this.vehicleType = value;
  }

  /**
   * Gets the value of the 'tollAmount' field.
   * @return The value of the 'tollAmount' field.
   */
  public java.lang.Integer getTollAmount() {
    return tollAmount;
  }

  /**
   * Sets the value of the 'tollAmount' field.
   * @param value the value to set.
   */
  public void setTollAmount(java.lang.Integer value) {
    this.tollAmount = value;
  }

  /**
   * Gets the value of the 'discountFee' field.
   * @return The value of the 'discountFee' field.
   */
  public java.lang.Integer getDiscountFee() {
    return discountFee;
  }

  /**
   * Sets the value of the 'discountFee' field.
   * @param value the value to set.
   */
  public void setDiscountFee(java.lang.Integer value) {
    this.discountFee = value;
  }

  /**
   * Gets the value of the 'vehPlate' field.
   * @return The value of the 'vehPlate' field.
   */
  public java.lang.CharSequence getVehPlate() {
    return vehPlate;
  }

  /**
   * Sets the value of the 'vehPlate' field.
   * @param value the value to set.
   */
  public void setVehPlate(java.lang.CharSequence value) {
    this.vehPlate = value;
  }

  /**
   * Gets the value of the 'vehColor' field.
   * @return The value of the 'vehColor' field.
   */
  public java.lang.CharSequence getVehColor() {
    return vehColor;
  }

  /**
   * Sets the value of the 'vehColor' field.
   * @param value the value to set.
   */
  public void setVehColor(java.lang.CharSequence value) {
    this.vehColor = value;
  }

  /**
   * Gets the value of the 'opTime' field.
   * @return The value of the 'opTime' field.
   */
  public java.lang.CharSequence getOpTime() {
    return opTime;
  }

  /**
   * Sets the value of the 'opTime' field.
   * @param value the value to set.
   */
  public void setOpTime(java.lang.CharSequence value) {
    this.opTime = value;
  }

  /**
   * Gets the value of the 'direction' field.
   * @return The value of the 'direction' field.
   */
  public java.lang.Integer getDirection() {
    return direction;
  }

  /**
   * Sets the value of the 'direction' field.
   * @param value the value to set.
   */
  public void setDirection(java.lang.Integer value) {
    this.direction = value;
  }

  /**
   * Gets the value of the 'vehStatus' field.
   * @return The value of the 'vehStatus' field.
   */
  public java.lang.Integer getVehStatus() {
    return vehStatus;
  }

  /**
   * Sets the value of the 'vehStatus' field.
   * @param value the value to set.
   */
  public void setVehStatus(java.lang.Integer value) {
    this.vehStatus = value;
  }

  /**
   * Gets the value of the 'obuElectrical' field.
   * @return The value of the 'obuElectrical' field.
   */
  public java.lang.Integer getObuElectrical() {
    return obuElectrical;
  }

  /**
   * Sets the value of the 'obuElectrical' field.
   * @param value the value to set.
   */
  public void setObuElectrical(java.lang.Integer value) {
    this.obuElectrical = value;
  }

  /**
   * Gets the value of the 'eevStatus' field.
   * @return The value of the 'eevStatus' field.
   */
  public java.lang.Integer getEevStatus() {
    return eevStatus;
  }

  /**
   * Sets the value of the 'eevStatus' field.
   * @param value the value to set.
   */
  public void setEevStatus(java.lang.Integer value) {
    this.eevStatus = value;
  }

  /**
   * Gets the value of the 'picSerialNo' field.
   * @return The value of the 'picSerialNo' field.
   */
  public java.lang.CharSequence getPicSerialNo() {
    return picSerialNo;
  }

  /**
   * Sets the value of the 'picSerialNo' field.
   * @param value the value to set.
   */
  public void setPicSerialNo(java.lang.CharSequence value) {
    this.picSerialNo = value;
  }

  /**
   * Gets the value of the 'spare1' field.
   * @return The value of the 'spare1' field.
   */
  public java.lang.Integer getSpare1() {
    return spare1;
  }

  /**
   * Sets the value of the 'spare1' field.
   * @param value the value to set.
   */
  public void setSpare1(java.lang.Integer value) {
    this.spare1 = value;
  }

  /**
   * Gets the value of the 'spare2' field.
   * @return The value of the 'spare2' field.
   */
  public java.lang.Integer getSpare2() {
    return spare2;
  }

  /**
   * Sets the value of the 'spare2' field.
   * @param value the value to set.
   */
  public void setSpare2(java.lang.Integer value) {
    this.spare2 = value;
  }

  /**
   * Gets the value of the 'spare3' field.
   * @return The value of the 'spare3' field.
   */
  public java.lang.CharSequence getSpare3() {
    return spare3;
  }

  /**
   * Sets the value of the 'spare3' field.
   * @param value the value to set.
   */
  public void setSpare3(java.lang.CharSequence value) {
    this.spare3 = value;
  }

  /**
   * Gets the value of the 'spare4' field.
   * @return The value of the 'spare4' field.
   */
  public java.lang.CharSequence getSpare4() {
    return spare4;
  }

  /**
   * Sets the value of the 'spare4' field.
   * @param value the value to set.
   */
  public void setSpare4(java.lang.CharSequence value) {
    this.spare4 = value;
  }

  /**
   * Creates a new FlagEtcPassListAvro RecordBuilder.
   * @return A new FlagEtcPassListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.FlagEtcPassListAvro.Builder newBuilder() {
    return new com.leatop.bee.web.po.FlagEtcPassListAvro.Builder();
  }

  /**
   * Creates a new FlagEtcPassListAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FlagEtcPassListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.FlagEtcPassListAvro.Builder newBuilder(com.leatop.bee.web.po.FlagEtcPassListAvro.Builder other) {
    return new com.leatop.bee.web.po.FlagEtcPassListAvro.Builder(other);
  }

  /**
   * Creates a new FlagEtcPassListAvro RecordBuilder by copying an existing FlagEtcPassListAvro instance.
   * @param other The existing instance to copy.
   * @return A new FlagEtcPassListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.FlagEtcPassListAvro.Builder newBuilder(com.leatop.bee.web.po.FlagEtcPassListAvro other) {
    return new com.leatop.bee.web.po.FlagEtcPassListAvro.Builder(other);
  }

  /**
   * RecordBuilder for FlagEtcPassListAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FlagEtcPassListAvro>
    implements org.apache.avro.data.RecordBuilder<FlagEtcPassListAvro> {

    private int recordNo;
    private java.lang.CharSequence serialNo;
    private int flagNetRoadID;
    private int flagRoadID;
    private int flagID;
    private int posId;
    private int laneNo;
    private int obuType;
    private int obuMacID;
    private java.lang.CharSequence obuNum;
    private java.lang.CharSequence etcTermCode;
    private int enRoadNo;
    private int enStationNo;
    private java.lang.CharSequence enTime;
    private java.lang.CharSequence cpuCardID;
    private int vehicleType;
    private int tollAmount;
    private int discountFee;
    private java.lang.CharSequence vehPlate;
    private java.lang.CharSequence vehColor;
    private java.lang.CharSequence opTime;
    private int direction;
    private int vehStatus;
    private int obuElectrical;
    private int eevStatus;
    private java.lang.CharSequence picSerialNo;
    private int spare1;
    private int spare2;
    private java.lang.CharSequence spare3;
    private java.lang.CharSequence spare4;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.leatop.bee.web.po.FlagEtcPassListAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.recordNo)) {
        this.recordNo = data().deepCopy(fields()[0].schema(), other.recordNo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serialNo)) {
        this.serialNo = data().deepCopy(fields()[1].schema(), other.serialNo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.flagNetRoadID)) {
        this.flagNetRoadID = data().deepCopy(fields()[2].schema(), other.flagNetRoadID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.flagRoadID)) {
        this.flagRoadID = data().deepCopy(fields()[3].schema(), other.flagRoadID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.flagID)) {
        this.flagID = data().deepCopy(fields()[4].schema(), other.flagID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.posId)) {
        this.posId = data().deepCopy(fields()[5].schema(), other.posId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.laneNo)) {
        this.laneNo = data().deepCopy(fields()[6].schema(), other.laneNo);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.obuType)) {
        this.obuType = data().deepCopy(fields()[7].schema(), other.obuType);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.obuMacID)) {
        this.obuMacID = data().deepCopy(fields()[8].schema(), other.obuMacID);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.obuNum)) {
        this.obuNum = data().deepCopy(fields()[9].schema(), other.obuNum);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.etcTermCode)) {
        this.etcTermCode = data().deepCopy(fields()[10].schema(), other.etcTermCode);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.enRoadNo)) {
        this.enRoadNo = data().deepCopy(fields()[11].schema(), other.enRoadNo);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.enStationNo)) {
        this.enStationNo = data().deepCopy(fields()[12].schema(), other.enStationNo);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.enTime)) {
        this.enTime = data().deepCopy(fields()[13].schema(), other.enTime);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.cpuCardID)) {
        this.cpuCardID = data().deepCopy(fields()[14].schema(), other.cpuCardID);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.vehicleType)) {
        this.vehicleType = data().deepCopy(fields()[15].schema(), other.vehicleType);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.tollAmount)) {
        this.tollAmount = data().deepCopy(fields()[16].schema(), other.tollAmount);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.discountFee)) {
        this.discountFee = data().deepCopy(fields()[17].schema(), other.discountFee);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.vehPlate)) {
        this.vehPlate = data().deepCopy(fields()[18].schema(), other.vehPlate);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.vehColor)) {
        this.vehColor = data().deepCopy(fields()[19].schema(), other.vehColor);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.opTime)) {
        this.opTime = data().deepCopy(fields()[20].schema(), other.opTime);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.direction)) {
        this.direction = data().deepCopy(fields()[21].schema(), other.direction);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.vehStatus)) {
        this.vehStatus = data().deepCopy(fields()[22].schema(), other.vehStatus);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.obuElectrical)) {
        this.obuElectrical = data().deepCopy(fields()[23].schema(), other.obuElectrical);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.eevStatus)) {
        this.eevStatus = data().deepCopy(fields()[24].schema(), other.eevStatus);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.picSerialNo)) {
        this.picSerialNo = data().deepCopy(fields()[25].schema(), other.picSerialNo);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.spare1)) {
        this.spare1 = data().deepCopy(fields()[26].schema(), other.spare1);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.spare2)) {
        this.spare2 = data().deepCopy(fields()[27].schema(), other.spare2);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.spare3)) {
        this.spare3 = data().deepCopy(fields()[28].schema(), other.spare3);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.spare4)) {
        this.spare4 = data().deepCopy(fields()[29].schema(), other.spare4);
        fieldSetFlags()[29] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FlagEtcPassListAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.leatop.bee.web.po.FlagEtcPassListAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.recordNo)) {
        this.recordNo = data().deepCopy(fields()[0].schema(), other.recordNo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serialNo)) {
        this.serialNo = data().deepCopy(fields()[1].schema(), other.serialNo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.flagNetRoadID)) {
        this.flagNetRoadID = data().deepCopy(fields()[2].schema(), other.flagNetRoadID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.flagRoadID)) {
        this.flagRoadID = data().deepCopy(fields()[3].schema(), other.flagRoadID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.flagID)) {
        this.flagID = data().deepCopy(fields()[4].schema(), other.flagID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.posId)) {
        this.posId = data().deepCopy(fields()[5].schema(), other.posId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.laneNo)) {
        this.laneNo = data().deepCopy(fields()[6].schema(), other.laneNo);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.obuType)) {
        this.obuType = data().deepCopy(fields()[7].schema(), other.obuType);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.obuMacID)) {
        this.obuMacID = data().deepCopy(fields()[8].schema(), other.obuMacID);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.obuNum)) {
        this.obuNum = data().deepCopy(fields()[9].schema(), other.obuNum);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.etcTermCode)) {
        this.etcTermCode = data().deepCopy(fields()[10].schema(), other.etcTermCode);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.enRoadNo)) {
        this.enRoadNo = data().deepCopy(fields()[11].schema(), other.enRoadNo);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.enStationNo)) {
        this.enStationNo = data().deepCopy(fields()[12].schema(), other.enStationNo);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.enTime)) {
        this.enTime = data().deepCopy(fields()[13].schema(), other.enTime);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.cpuCardID)) {
        this.cpuCardID = data().deepCopy(fields()[14].schema(), other.cpuCardID);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.vehicleType)) {
        this.vehicleType = data().deepCopy(fields()[15].schema(), other.vehicleType);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.tollAmount)) {
        this.tollAmount = data().deepCopy(fields()[16].schema(), other.tollAmount);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.discountFee)) {
        this.discountFee = data().deepCopy(fields()[17].schema(), other.discountFee);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.vehPlate)) {
        this.vehPlate = data().deepCopy(fields()[18].schema(), other.vehPlate);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.vehColor)) {
        this.vehColor = data().deepCopy(fields()[19].schema(), other.vehColor);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.opTime)) {
        this.opTime = data().deepCopy(fields()[20].schema(), other.opTime);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.direction)) {
        this.direction = data().deepCopy(fields()[21].schema(), other.direction);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.vehStatus)) {
        this.vehStatus = data().deepCopy(fields()[22].schema(), other.vehStatus);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.obuElectrical)) {
        this.obuElectrical = data().deepCopy(fields()[23].schema(), other.obuElectrical);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.eevStatus)) {
        this.eevStatus = data().deepCopy(fields()[24].schema(), other.eevStatus);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.picSerialNo)) {
        this.picSerialNo = data().deepCopy(fields()[25].schema(), other.picSerialNo);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.spare1)) {
        this.spare1 = data().deepCopy(fields()[26].schema(), other.spare1);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.spare2)) {
        this.spare2 = data().deepCopy(fields()[27].schema(), other.spare2);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.spare3)) {
        this.spare3 = data().deepCopy(fields()[28].schema(), other.spare3);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.spare4)) {
        this.spare4 = data().deepCopy(fields()[29].schema(), other.spare4);
        fieldSetFlags()[29] = true;
      }
    }

    /**
      * Gets the value of the 'recordNo' field.
      * @return The value.
      */
    public java.lang.Integer getRecordNo() {
      return recordNo;
    }

    /**
      * Sets the value of the 'recordNo' field.
      * @param value The value of 'recordNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setRecordNo(int value) {
      validate(fields()[0], value);
      this.recordNo = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'recordNo' field has been set.
      * @return True if the 'recordNo' field has been set, false otherwise.
      */
    public boolean hasRecordNo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'recordNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearRecordNo() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'serialNo' field.
      * @return The value.
      */
    public java.lang.CharSequence getSerialNo() {
      return serialNo;
    }

    /**
      * Sets the value of the 'serialNo' field.
      * @param value The value of 'serialNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setSerialNo(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.serialNo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'serialNo' field has been set.
      * @return True if the 'serialNo' field has been set, false otherwise.
      */
    public boolean hasSerialNo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'serialNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearSerialNo() {
      serialNo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagNetRoadID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagNetRoadID() {
      return flagNetRoadID;
    }

    /**
      * Sets the value of the 'flagNetRoadID' field.
      * @param value The value of 'flagNetRoadID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setFlagNetRoadID(int value) {
      validate(fields()[2], value);
      this.flagNetRoadID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'flagNetRoadID' field has been set.
      * @return True if the 'flagNetRoadID' field has been set, false otherwise.
      */
    public boolean hasFlagNetRoadID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'flagNetRoadID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearFlagNetRoadID() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagRoadID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagRoadID() {
      return flagRoadID;
    }

    /**
      * Sets the value of the 'flagRoadID' field.
      * @param value The value of 'flagRoadID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setFlagRoadID(int value) {
      validate(fields()[3], value);
      this.flagRoadID = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'flagRoadID' field has been set.
      * @return True if the 'flagRoadID' field has been set, false otherwise.
      */
    public boolean hasFlagRoadID() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'flagRoadID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearFlagRoadID() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagID() {
      return flagID;
    }

    /**
      * Sets the value of the 'flagID' field.
      * @param value The value of 'flagID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setFlagID(int value) {
      validate(fields()[4], value);
      this.flagID = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'flagID' field has been set.
      * @return True if the 'flagID' field has been set, false otherwise.
      */
    public boolean hasFlagID() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'flagID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearFlagID() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'posId' field.
      * @return The value.
      */
    public java.lang.Integer getPosId() {
      return posId;
    }

    /**
      * Sets the value of the 'posId' field.
      * @param value The value of 'posId'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setPosId(int value) {
      validate(fields()[5], value);
      this.posId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'posId' field has been set.
      * @return True if the 'posId' field has been set, false otherwise.
      */
    public boolean hasPosId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'posId' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearPosId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'laneNo' field.
      * @return The value.
      */
    public java.lang.Integer getLaneNo() {
      return laneNo;
    }

    /**
      * Sets the value of the 'laneNo' field.
      * @param value The value of 'laneNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setLaneNo(int value) {
      validate(fields()[6], value);
      this.laneNo = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'laneNo' field has been set.
      * @return True if the 'laneNo' field has been set, false otherwise.
      */
    public boolean hasLaneNo() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'laneNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearLaneNo() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'obuType' field.
      * @return The value.
      */
    public java.lang.Integer getObuType() {
      return obuType;
    }

    /**
      * Sets the value of the 'obuType' field.
      * @param value The value of 'obuType'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setObuType(int value) {
      validate(fields()[7], value);
      this.obuType = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'obuType' field has been set.
      * @return True if the 'obuType' field has been set, false otherwise.
      */
    public boolean hasObuType() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'obuType' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearObuType() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'obuMacID' field.
      * @return The value.
      */
    public java.lang.Integer getObuMacID() {
      return obuMacID;
    }

    /**
      * Sets the value of the 'obuMacID' field.
      * @param value The value of 'obuMacID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setObuMacID(int value) {
      validate(fields()[8], value);
      this.obuMacID = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'obuMacID' field has been set.
      * @return True if the 'obuMacID' field has been set, false otherwise.
      */
    public boolean hasObuMacID() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'obuMacID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearObuMacID() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'obuNum' field.
      * @return The value.
      */
    public java.lang.CharSequence getObuNum() {
      return obuNum;
    }

    /**
      * Sets the value of the 'obuNum' field.
      * @param value The value of 'obuNum'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setObuNum(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.obuNum = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'obuNum' field has been set.
      * @return True if the 'obuNum' field has been set, false otherwise.
      */
    public boolean hasObuNum() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'obuNum' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearObuNum() {
      obuNum = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'etcTermCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getEtcTermCode() {
      return etcTermCode;
    }

    /**
      * Sets the value of the 'etcTermCode' field.
      * @param value The value of 'etcTermCode'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setEtcTermCode(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.etcTermCode = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'etcTermCode' field has been set.
      * @return True if the 'etcTermCode' field has been set, false otherwise.
      */
    public boolean hasEtcTermCode() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'etcTermCode' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearEtcTermCode() {
      etcTermCode = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'enRoadNo' field.
      * @return The value.
      */
    public java.lang.Integer getEnRoadNo() {
      return enRoadNo;
    }

    /**
      * Sets the value of the 'enRoadNo' field.
      * @param value The value of 'enRoadNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setEnRoadNo(int value) {
      validate(fields()[11], value);
      this.enRoadNo = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'enRoadNo' field has been set.
      * @return True if the 'enRoadNo' field has been set, false otherwise.
      */
    public boolean hasEnRoadNo() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'enRoadNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearEnRoadNo() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'enStationNo' field.
      * @return The value.
      */
    public java.lang.Integer getEnStationNo() {
      return enStationNo;
    }

    /**
      * Sets the value of the 'enStationNo' field.
      * @param value The value of 'enStationNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setEnStationNo(int value) {
      validate(fields()[12], value);
      this.enStationNo = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'enStationNo' field has been set.
      * @return True if the 'enStationNo' field has been set, false otherwise.
      */
    public boolean hasEnStationNo() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'enStationNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearEnStationNo() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'enTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getEnTime() {
      return enTime;
    }

    /**
      * Sets the value of the 'enTime' field.
      * @param value The value of 'enTime'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setEnTime(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.enTime = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'enTime' field has been set.
      * @return True if the 'enTime' field has been set, false otherwise.
      */
    public boolean hasEnTime() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'enTime' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearEnTime() {
      enTime = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'cpuCardID' field.
      * @return The value.
      */
    public java.lang.CharSequence getCpuCardID() {
      return cpuCardID;
    }

    /**
      * Sets the value of the 'cpuCardID' field.
      * @param value The value of 'cpuCardID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setCpuCardID(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.cpuCardID = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'cpuCardID' field has been set.
      * @return True if the 'cpuCardID' field has been set, false otherwise.
      */
    public boolean hasCpuCardID() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'cpuCardID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearCpuCardID() {
      cpuCardID = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehicleType' field.
      * @return The value.
      */
    public java.lang.Integer getVehicleType() {
      return vehicleType;
    }

    /**
      * Sets the value of the 'vehicleType' field.
      * @param value The value of 'vehicleType'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setVehicleType(int value) {
      validate(fields()[15], value);
      this.vehicleType = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'vehicleType' field has been set.
      * @return True if the 'vehicleType' field has been set, false otherwise.
      */
    public boolean hasVehicleType() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'vehicleType' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearVehicleType() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'tollAmount' field.
      * @return The value.
      */
    public java.lang.Integer getTollAmount() {
      return tollAmount;
    }

    /**
      * Sets the value of the 'tollAmount' field.
      * @param value The value of 'tollAmount'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setTollAmount(int value) {
      validate(fields()[16], value);
      this.tollAmount = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'tollAmount' field has been set.
      * @return True if the 'tollAmount' field has been set, false otherwise.
      */
    public boolean hasTollAmount() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'tollAmount' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearTollAmount() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'discountFee' field.
      * @return The value.
      */
    public java.lang.Integer getDiscountFee() {
      return discountFee;
    }

    /**
      * Sets the value of the 'discountFee' field.
      * @param value The value of 'discountFee'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setDiscountFee(int value) {
      validate(fields()[17], value);
      this.discountFee = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'discountFee' field has been set.
      * @return True if the 'discountFee' field has been set, false otherwise.
      */
    public boolean hasDiscountFee() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'discountFee' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearDiscountFee() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehPlate' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehPlate() {
      return vehPlate;
    }

    /**
      * Sets the value of the 'vehPlate' field.
      * @param value The value of 'vehPlate'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setVehPlate(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.vehPlate = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'vehPlate' field has been set.
      * @return True if the 'vehPlate' field has been set, false otherwise.
      */
    public boolean hasVehPlate() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'vehPlate' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearVehPlate() {
      vehPlate = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehColor' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehColor() {
      return vehColor;
    }

    /**
      * Sets the value of the 'vehColor' field.
      * @param value The value of 'vehColor'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setVehColor(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.vehColor = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'vehColor' field has been set.
      * @return True if the 'vehColor' field has been set, false otherwise.
      */
    public boolean hasVehColor() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'vehColor' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearVehColor() {
      vehColor = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'opTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getOpTime() {
      return opTime;
    }

    /**
      * Sets the value of the 'opTime' field.
      * @param value The value of 'opTime'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setOpTime(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.opTime = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'opTime' field has been set.
      * @return True if the 'opTime' field has been set, false otherwise.
      */
    public boolean hasOpTime() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'opTime' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearOpTime() {
      opTime = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'direction' field.
      * @return The value.
      */
    public java.lang.Integer getDirection() {
      return direction;
    }

    /**
      * Sets the value of the 'direction' field.
      * @param value The value of 'direction'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setDirection(int value) {
      validate(fields()[21], value);
      this.direction = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'direction' field has been set.
      * @return True if the 'direction' field has been set, false otherwise.
      */
    public boolean hasDirection() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'direction' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearDirection() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehStatus' field.
      * @return The value.
      */
    public java.lang.Integer getVehStatus() {
      return vehStatus;
    }

    /**
      * Sets the value of the 'vehStatus' field.
      * @param value The value of 'vehStatus'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setVehStatus(int value) {
      validate(fields()[22], value);
      this.vehStatus = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'vehStatus' field has been set.
      * @return True if the 'vehStatus' field has been set, false otherwise.
      */
    public boolean hasVehStatus() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'vehStatus' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearVehStatus() {
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'obuElectrical' field.
      * @return The value.
      */
    public java.lang.Integer getObuElectrical() {
      return obuElectrical;
    }

    /**
      * Sets the value of the 'obuElectrical' field.
      * @param value The value of 'obuElectrical'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setObuElectrical(int value) {
      validate(fields()[23], value);
      this.obuElectrical = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'obuElectrical' field has been set.
      * @return True if the 'obuElectrical' field has been set, false otherwise.
      */
    public boolean hasObuElectrical() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'obuElectrical' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearObuElectrical() {
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'eevStatus' field.
      * @return The value.
      */
    public java.lang.Integer getEevStatus() {
      return eevStatus;
    }

    /**
      * Sets the value of the 'eevStatus' field.
      * @param value The value of 'eevStatus'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setEevStatus(int value) {
      validate(fields()[24], value);
      this.eevStatus = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'eevStatus' field has been set.
      * @return True if the 'eevStatus' field has been set, false otherwise.
      */
    public boolean hasEevStatus() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'eevStatus' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearEevStatus() {
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'picSerialNo' field.
      * @return The value.
      */
    public java.lang.CharSequence getPicSerialNo() {
      return picSerialNo;
    }

    /**
      * Sets the value of the 'picSerialNo' field.
      * @param value The value of 'picSerialNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setPicSerialNo(java.lang.CharSequence value) {
      validate(fields()[25], value);
      this.picSerialNo = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'picSerialNo' field has been set.
      * @return True if the 'picSerialNo' field has been set, false otherwise.
      */
    public boolean hasPicSerialNo() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'picSerialNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearPicSerialNo() {
      picSerialNo = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'spare1' field.
      * @return The value.
      */
    public java.lang.Integer getSpare1() {
      return spare1;
    }

    /**
      * Sets the value of the 'spare1' field.
      * @param value The value of 'spare1'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setSpare1(int value) {
      validate(fields()[26], value);
      this.spare1 = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'spare1' field has been set.
      * @return True if the 'spare1' field has been set, false otherwise.
      */
    public boolean hasSpare1() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'spare1' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearSpare1() {
      fieldSetFlags()[26] = false;
      return this;
    }

    /**
      * Gets the value of the 'spare2' field.
      * @return The value.
      */
    public java.lang.Integer getSpare2() {
      return spare2;
    }

    /**
      * Sets the value of the 'spare2' field.
      * @param value The value of 'spare2'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setSpare2(int value) {
      validate(fields()[27], value);
      this.spare2 = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /**
      * Checks whether the 'spare2' field has been set.
      * @return True if the 'spare2' field has been set, false otherwise.
      */
    public boolean hasSpare2() {
      return fieldSetFlags()[27];
    }


    /**
      * Clears the value of the 'spare2' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearSpare2() {
      fieldSetFlags()[27] = false;
      return this;
    }

    /**
      * Gets the value of the 'spare3' field.
      * @return The value.
      */
    public java.lang.CharSequence getSpare3() {
      return spare3;
    }

    /**
      * Sets the value of the 'spare3' field.
      * @param value The value of 'spare3'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setSpare3(java.lang.CharSequence value) {
      validate(fields()[28], value);
      this.spare3 = value;
      fieldSetFlags()[28] = true;
      return this;
    }

    /**
      * Checks whether the 'spare3' field has been set.
      * @return True if the 'spare3' field has been set, false otherwise.
      */
    public boolean hasSpare3() {
      return fieldSetFlags()[28];
    }


    /**
      * Clears the value of the 'spare3' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearSpare3() {
      spare3 = null;
      fieldSetFlags()[28] = false;
      return this;
    }

    /**
      * Gets the value of the 'spare4' field.
      * @return The value.
      */
    public java.lang.CharSequence getSpare4() {
      return spare4;
    }

    /**
      * Sets the value of the 'spare4' field.
      * @param value The value of 'spare4'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder setSpare4(java.lang.CharSequence value) {
      validate(fields()[29], value);
      this.spare4 = value;
      fieldSetFlags()[29] = true;
      return this;
    }

    /**
      * Checks whether the 'spare4' field has been set.
      * @return True if the 'spare4' field has been set, false otherwise.
      */
    public boolean hasSpare4() {
      return fieldSetFlags()[29];
    }


    /**
      * Clears the value of the 'spare4' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagEtcPassListAvro.Builder clearSpare4() {
      spare4 = null;
      fieldSetFlags()[29] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FlagEtcPassListAvro build() {
      try {
        FlagEtcPassListAvro record = new FlagEtcPassListAvro();
        record.recordNo = fieldSetFlags()[0] ? this.recordNo : (java.lang.Integer) defaultValue(fields()[0]);
        record.serialNo = fieldSetFlags()[1] ? this.serialNo : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.flagNetRoadID = fieldSetFlags()[2] ? this.flagNetRoadID : (java.lang.Integer) defaultValue(fields()[2]);
        record.flagRoadID = fieldSetFlags()[3] ? this.flagRoadID : (java.lang.Integer) defaultValue(fields()[3]);
        record.flagID = fieldSetFlags()[4] ? this.flagID : (java.lang.Integer) defaultValue(fields()[4]);
        record.posId = fieldSetFlags()[5] ? this.posId : (java.lang.Integer) defaultValue(fields()[5]);
        record.laneNo = fieldSetFlags()[6] ? this.laneNo : (java.lang.Integer) defaultValue(fields()[6]);
        record.obuType = fieldSetFlags()[7] ? this.obuType : (java.lang.Integer) defaultValue(fields()[7]);
        record.obuMacID = fieldSetFlags()[8] ? this.obuMacID : (java.lang.Integer) defaultValue(fields()[8]);
        record.obuNum = fieldSetFlags()[9] ? this.obuNum : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.etcTermCode = fieldSetFlags()[10] ? this.etcTermCode : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.enRoadNo = fieldSetFlags()[11] ? this.enRoadNo : (java.lang.Integer) defaultValue(fields()[11]);
        record.enStationNo = fieldSetFlags()[12] ? this.enStationNo : (java.lang.Integer) defaultValue(fields()[12]);
        record.enTime = fieldSetFlags()[13] ? this.enTime : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.cpuCardID = fieldSetFlags()[14] ? this.cpuCardID : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.vehicleType = fieldSetFlags()[15] ? this.vehicleType : (java.lang.Integer) defaultValue(fields()[15]);
        record.tollAmount = fieldSetFlags()[16] ? this.tollAmount : (java.lang.Integer) defaultValue(fields()[16]);
        record.discountFee = fieldSetFlags()[17] ? this.discountFee : (java.lang.Integer) defaultValue(fields()[17]);
        record.vehPlate = fieldSetFlags()[18] ? this.vehPlate : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.vehColor = fieldSetFlags()[19] ? this.vehColor : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.opTime = fieldSetFlags()[20] ? this.opTime : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.direction = fieldSetFlags()[21] ? this.direction : (java.lang.Integer) defaultValue(fields()[21]);
        record.vehStatus = fieldSetFlags()[22] ? this.vehStatus : (java.lang.Integer) defaultValue(fields()[22]);
        record.obuElectrical = fieldSetFlags()[23] ? this.obuElectrical : (java.lang.Integer) defaultValue(fields()[23]);
        record.eevStatus = fieldSetFlags()[24] ? this.eevStatus : (java.lang.Integer) defaultValue(fields()[24]);
        record.picSerialNo = fieldSetFlags()[25] ? this.picSerialNo : (java.lang.CharSequence) defaultValue(fields()[25]);
        record.spare1 = fieldSetFlags()[26] ? this.spare1 : (java.lang.Integer) defaultValue(fields()[26]);
        record.spare2 = fieldSetFlags()[27] ? this.spare2 : (java.lang.Integer) defaultValue(fields()[27]);
        record.spare3 = fieldSetFlags()[28] ? this.spare3 : (java.lang.CharSequence) defaultValue(fields()[28]);
        record.spare4 = fieldSetFlags()[29] ? this.spare4 : (java.lang.CharSequence) defaultValue(fields()[29]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FlagEtcPassListAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<FlagEtcPassListAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FlagEtcPassListAvro>
    READER$ = (org.apache.avro.io.DatumReader<FlagEtcPassListAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
