/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leatop.bee.web.po;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FlagCarPassListAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5090543781473294280L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FlagCarPassListAvro\",\"namespace\":\"com.leatop.bee.web.po\",\"fields\":[{\"name\":\"recordNo\",\"type\":\"int\"},{\"name\":\"picSerialNo\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"flagNetRoadID\",\"type\":\"int\"},{\"name\":\"flagRoadID\",\"type\":\"int\"},{\"name\":\"roadId\",\"type\":\"int\"},{\"name\":\"flagID\",\"type\":\"int\"},{\"name\":\"posId\",\"type\":\"int\"},{\"name\":\"laneNo\",\"type\":\"int\"},{\"name\":\"deviceID\",\"type\":\"int\"},{\"name\":\"opTime\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"vehPlate\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"vehColor\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"vehSpeed\",\"type\":\"int\"},{\"name\":\"vehBodyColorNo\",\"type\":\"int\"},{\"name\":\"vehBodyDeepNo\",\"type\":\"int\"},{\"name\":\"vehTypeNo\",\"type\":\"int\"},{\"name\":\"plateTypeNo\",\"type\":\"int\"},{\"name\":\"images\",\"type\":\"bytes\",\"default\":\"null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FlagCarPassListAvro> ENCODER =
      new BinaryMessageEncoder<FlagCarPassListAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FlagCarPassListAvro> DECODER =
      new BinaryMessageDecoder<FlagCarPassListAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FlagCarPassListAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FlagCarPassListAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FlagCarPassListAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FlagCarPassListAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FlagCarPassListAvro from a ByteBuffer. */
  public static FlagCarPassListAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int recordNo;
  @Deprecated public java.lang.CharSequence picSerialNo;
  @Deprecated public int flagNetRoadID;
  @Deprecated public int flagRoadID;
  @Deprecated public int roadId;
  @Deprecated public int flagID;
  @Deprecated public int posId;
  @Deprecated public int laneNo;
  @Deprecated public int deviceID;
  @Deprecated public java.lang.CharSequence opTime;
  @Deprecated public java.lang.CharSequence vehPlate;
  @Deprecated public java.lang.CharSequence vehColor;
  @Deprecated public int vehSpeed;
  @Deprecated public int vehBodyColorNo;
  @Deprecated public int vehBodyDeepNo;
  @Deprecated public int vehTypeNo;
  @Deprecated public int plateTypeNo;
  @Deprecated public java.nio.ByteBuffer images;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FlagCarPassListAvro() {}

  /**
   * All-args constructor.
   * @param recordNo The new value for recordNo
   * @param picSerialNo The new value for picSerialNo
   * @param flagNetRoadID The new value for flagNetRoadID
   * @param flagRoadID The new value for flagRoadID
   * @param roadId The new value for roadId
   * @param flagID The new value for flagID
   * @param posId The new value for posId
   * @param laneNo The new value for laneNo
   * @param deviceID The new value for deviceID
   * @param opTime The new value for opTime
   * @param vehPlate The new value for vehPlate
   * @param vehColor The new value for vehColor
   * @param vehSpeed The new value for vehSpeed
   * @param vehBodyColorNo The new value for vehBodyColorNo
   * @param vehBodyDeepNo The new value for vehBodyDeepNo
   * @param vehTypeNo The new value for vehTypeNo
   * @param plateTypeNo The new value for plateTypeNo
   * @param images The new value for images
   */
  public FlagCarPassListAvro(java.lang.Integer recordNo, java.lang.CharSequence picSerialNo, java.lang.Integer flagNetRoadID, java.lang.Integer flagRoadID, java.lang.Integer roadId, java.lang.Integer flagID, java.lang.Integer posId, java.lang.Integer laneNo, java.lang.Integer deviceID, java.lang.CharSequence opTime, java.lang.CharSequence vehPlate, java.lang.CharSequence vehColor, java.lang.Integer vehSpeed, java.lang.Integer vehBodyColorNo, java.lang.Integer vehBodyDeepNo, java.lang.Integer vehTypeNo, java.lang.Integer plateTypeNo, java.nio.ByteBuffer images) {
    this.recordNo = recordNo;
    this.picSerialNo = picSerialNo;
    this.flagNetRoadID = flagNetRoadID;
    this.flagRoadID = flagRoadID;
    this.roadId = roadId;
    this.flagID = flagID;
    this.posId = posId;
    this.laneNo = laneNo;
    this.deviceID = deviceID;
    this.opTime = opTime;
    this.vehPlate = vehPlate;
    this.vehColor = vehColor;
    this.vehSpeed = vehSpeed;
    this.vehBodyColorNo = vehBodyColorNo;
    this.vehBodyDeepNo = vehBodyDeepNo;
    this.vehTypeNo = vehTypeNo;
    this.plateTypeNo = plateTypeNo;
    this.images = images;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return recordNo;
    case 1: return picSerialNo;
    case 2: return flagNetRoadID;
    case 3: return flagRoadID;
    case 4: return roadId;
    case 5: return flagID;
    case 6: return posId;
    case 7: return laneNo;
    case 8: return deviceID;
    case 9: return opTime;
    case 10: return vehPlate;
    case 11: return vehColor;
    case 12: return vehSpeed;
    case 13: return vehBodyColorNo;
    case 14: return vehBodyDeepNo;
    case 15: return vehTypeNo;
    case 16: return plateTypeNo;
    case 17: return images;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: recordNo = (java.lang.Integer)value$; break;
    case 1: picSerialNo = (java.lang.CharSequence)value$; break;
    case 2: flagNetRoadID = (java.lang.Integer)value$; break;
    case 3: flagRoadID = (java.lang.Integer)value$; break;
    case 4: roadId = (java.lang.Integer)value$; break;
    case 5: flagID = (java.lang.Integer)value$; break;
    case 6: posId = (java.lang.Integer)value$; break;
    case 7: laneNo = (java.lang.Integer)value$; break;
    case 8: deviceID = (java.lang.Integer)value$; break;
    case 9: opTime = (java.lang.CharSequence)value$; break;
    case 10: vehPlate = (java.lang.CharSequence)value$; break;
    case 11: vehColor = (java.lang.CharSequence)value$; break;
    case 12: vehSpeed = (java.lang.Integer)value$; break;
    case 13: vehBodyColorNo = (java.lang.Integer)value$; break;
    case 14: vehBodyDeepNo = (java.lang.Integer)value$; break;
    case 15: vehTypeNo = (java.lang.Integer)value$; break;
    case 16: plateTypeNo = (java.lang.Integer)value$; break;
    case 17: images = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'recordNo' field.
   * @return The value of the 'recordNo' field.
   */
  public java.lang.Integer getRecordNo() {
    return recordNo;
  }

  /**
   * Sets the value of the 'recordNo' field.
   * @param value the value to set.
   */
  public void setRecordNo(java.lang.Integer value) {
    this.recordNo = value;
  }

  /**
   * Gets the value of the 'picSerialNo' field.
   * @return The value of the 'picSerialNo' field.
   */
  public java.lang.CharSequence getPicSerialNo() {
    return picSerialNo;
  }

  /**
   * Sets the value of the 'picSerialNo' field.
   * @param value the value to set.
   */
  public void setPicSerialNo(java.lang.CharSequence value) {
    this.picSerialNo = value;
  }

  /**
   * Gets the value of the 'flagNetRoadID' field.
   * @return The value of the 'flagNetRoadID' field.
   */
  public java.lang.Integer getFlagNetRoadID() {
    return flagNetRoadID;
  }

  /**
   * Sets the value of the 'flagNetRoadID' field.
   * @param value the value to set.
   */
  public void setFlagNetRoadID(java.lang.Integer value) {
    this.flagNetRoadID = value;
  }

  /**
   * Gets the value of the 'flagRoadID' field.
   * @return The value of the 'flagRoadID' field.
   */
  public java.lang.Integer getFlagRoadID() {
    return flagRoadID;
  }

  /**
   * Sets the value of the 'flagRoadID' field.
   * @param value the value to set.
   */
  public void setFlagRoadID(java.lang.Integer value) {
    this.flagRoadID = value;
  }

  /**
   * Gets the value of the 'roadId' field.
   * @return The value of the 'roadId' field.
   */
  public java.lang.Integer getRoadId() {
    return roadId;
  }

  /**
   * Sets the value of the 'roadId' field.
   * @param value the value to set.
   */
  public void setRoadId(java.lang.Integer value) {
    this.roadId = value;
  }

  /**
   * Gets the value of the 'flagID' field.
   * @return The value of the 'flagID' field.
   */
  public java.lang.Integer getFlagID() {
    return flagID;
  }

  /**
   * Sets the value of the 'flagID' field.
   * @param value the value to set.
   */
  public void setFlagID(java.lang.Integer value) {
    this.flagID = value;
  }

  /**
   * Gets the value of the 'posId' field.
   * @return The value of the 'posId' field.
   */
  public java.lang.Integer getPosId() {
    return posId;
  }

  /**
   * Sets the value of the 'posId' field.
   * @param value the value to set.
   */
  public void setPosId(java.lang.Integer value) {
    this.posId = value;
  }

  /**
   * Gets the value of the 'laneNo' field.
   * @return The value of the 'laneNo' field.
   */
  public java.lang.Integer getLaneNo() {
    return laneNo;
  }

  /**
   * Sets the value of the 'laneNo' field.
   * @param value the value to set.
   */
  public void setLaneNo(java.lang.Integer value) {
    this.laneNo = value;
  }

  /**
   * Gets the value of the 'deviceID' field.
   * @return The value of the 'deviceID' field.
   */
  public java.lang.Integer getDeviceID() {
    return deviceID;
  }

  /**
   * Sets the value of the 'deviceID' field.
   * @param value the value to set.
   */
  public void setDeviceID(java.lang.Integer value) {
    this.deviceID = value;
  }

  /**
   * Gets the value of the 'opTime' field.
   * @return The value of the 'opTime' field.
   */
  public java.lang.CharSequence getOpTime() {
    return opTime;
  }

  /**
   * Sets the value of the 'opTime' field.
   * @param value the value to set.
   */
  public void setOpTime(java.lang.CharSequence value) {
    this.opTime = value;
  }

  /**
   * Gets the value of the 'vehPlate' field.
   * @return The value of the 'vehPlate' field.
   */
  public java.lang.CharSequence getVehPlate() {
    return vehPlate;
  }

  /**
   * Sets the value of the 'vehPlate' field.
   * @param value the value to set.
   */
  public void setVehPlate(java.lang.CharSequence value) {
    this.vehPlate = value;
  }

  /**
   * Gets the value of the 'vehColor' field.
   * @return The value of the 'vehColor' field.
   */
  public java.lang.CharSequence getVehColor() {
    return vehColor;
  }

  /**
   * Sets the value of the 'vehColor' field.
   * @param value the value to set.
   */
  public void setVehColor(java.lang.CharSequence value) {
    this.vehColor = value;
  }

  /**
   * Gets the value of the 'vehSpeed' field.
   * @return The value of the 'vehSpeed' field.
   */
  public java.lang.Integer getVehSpeed() {
    return vehSpeed;
  }

  /**
   * Sets the value of the 'vehSpeed' field.
   * @param value the value to set.
   */
  public void setVehSpeed(java.lang.Integer value) {
    this.vehSpeed = value;
  }

  /**
   * Gets the value of the 'vehBodyColorNo' field.
   * @return The value of the 'vehBodyColorNo' field.
   */
  public java.lang.Integer getVehBodyColorNo() {
    return vehBodyColorNo;
  }

  /**
   * Sets the value of the 'vehBodyColorNo' field.
   * @param value the value to set.
   */
  public void setVehBodyColorNo(java.lang.Integer value) {
    this.vehBodyColorNo = value;
  }

  /**
   * Gets the value of the 'vehBodyDeepNo' field.
   * @return The value of the 'vehBodyDeepNo' field.
   */
  public java.lang.Integer getVehBodyDeepNo() {
    return vehBodyDeepNo;
  }

  /**
   * Sets the value of the 'vehBodyDeepNo' field.
   * @param value the value to set.
   */
  public void setVehBodyDeepNo(java.lang.Integer value) {
    this.vehBodyDeepNo = value;
  }

  /**
   * Gets the value of the 'vehTypeNo' field.
   * @return The value of the 'vehTypeNo' field.
   */
  public java.lang.Integer getVehTypeNo() {
    return vehTypeNo;
  }

  /**
   * Sets the value of the 'vehTypeNo' field.
   * @param value the value to set.
   */
  public void setVehTypeNo(java.lang.Integer value) {
    this.vehTypeNo = value;
  }

  /**
   * Gets the value of the 'plateTypeNo' field.
   * @return The value of the 'plateTypeNo' field.
   */
  public java.lang.Integer getPlateTypeNo() {
    return plateTypeNo;
  }

  /**
   * Sets the value of the 'plateTypeNo' field.
   * @param value the value to set.
   */
  public void setPlateTypeNo(java.lang.Integer value) {
    this.plateTypeNo = value;
  }

  /**
   * Gets the value of the 'images' field.
   * @return The value of the 'images' field.
   */
  public java.nio.ByteBuffer getImages() {
    return images;
  }

  /**
   * Sets the value of the 'images' field.
   * @param value the value to set.
   */
  public void setImages(java.nio.ByteBuffer value) {
    this.images = value;
  }

  /**
   * Creates a new FlagCarPassListAvro RecordBuilder.
   * @return A new FlagCarPassListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.FlagCarPassListAvro.Builder newBuilder() {
    return new com.leatop.bee.web.po.FlagCarPassListAvro.Builder();
  }

  /**
   * Creates a new FlagCarPassListAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FlagCarPassListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.FlagCarPassListAvro.Builder newBuilder(com.leatop.bee.web.po.FlagCarPassListAvro.Builder other) {
    return new com.leatop.bee.web.po.FlagCarPassListAvro.Builder(other);
  }

  /**
   * Creates a new FlagCarPassListAvro RecordBuilder by copying an existing FlagCarPassListAvro instance.
   * @param other The existing instance to copy.
   * @return A new FlagCarPassListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.FlagCarPassListAvro.Builder newBuilder(com.leatop.bee.web.po.FlagCarPassListAvro other) {
    return new com.leatop.bee.web.po.FlagCarPassListAvro.Builder(other);
  }

  /**
   * RecordBuilder for FlagCarPassListAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FlagCarPassListAvro>
    implements org.apache.avro.data.RecordBuilder<FlagCarPassListAvro> {

    private int recordNo;
    private java.lang.CharSequence picSerialNo;
    private int flagNetRoadID;
    private int flagRoadID;
    private int roadId;
    private int flagID;
    private int posId;
    private int laneNo;
    private int deviceID;
    private java.lang.CharSequence opTime;
    private java.lang.CharSequence vehPlate;
    private java.lang.CharSequence vehColor;
    private int vehSpeed;
    private int vehBodyColorNo;
    private int vehBodyDeepNo;
    private int vehTypeNo;
    private int plateTypeNo;
    private java.nio.ByteBuffer images;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.leatop.bee.web.po.FlagCarPassListAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.recordNo)) {
        this.recordNo = data().deepCopy(fields()[0].schema(), other.recordNo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.picSerialNo)) {
        this.picSerialNo = data().deepCopy(fields()[1].schema(), other.picSerialNo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.flagNetRoadID)) {
        this.flagNetRoadID = data().deepCopy(fields()[2].schema(), other.flagNetRoadID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.flagRoadID)) {
        this.flagRoadID = data().deepCopy(fields()[3].schema(), other.flagRoadID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.roadId)) {
        this.roadId = data().deepCopy(fields()[4].schema(), other.roadId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.flagID)) {
        this.flagID = data().deepCopy(fields()[5].schema(), other.flagID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.posId)) {
        this.posId = data().deepCopy(fields()[6].schema(), other.posId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.laneNo)) {
        this.laneNo = data().deepCopy(fields()[7].schema(), other.laneNo);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.deviceID)) {
        this.deviceID = data().deepCopy(fields()[8].schema(), other.deviceID);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.opTime)) {
        this.opTime = data().deepCopy(fields()[9].schema(), other.opTime);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.vehPlate)) {
        this.vehPlate = data().deepCopy(fields()[10].schema(), other.vehPlate);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.vehColor)) {
        this.vehColor = data().deepCopy(fields()[11].schema(), other.vehColor);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.vehSpeed)) {
        this.vehSpeed = data().deepCopy(fields()[12].schema(), other.vehSpeed);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.vehBodyColorNo)) {
        this.vehBodyColorNo = data().deepCopy(fields()[13].schema(), other.vehBodyColorNo);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.vehBodyDeepNo)) {
        this.vehBodyDeepNo = data().deepCopy(fields()[14].schema(), other.vehBodyDeepNo);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.vehTypeNo)) {
        this.vehTypeNo = data().deepCopy(fields()[15].schema(), other.vehTypeNo);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.plateTypeNo)) {
        this.plateTypeNo = data().deepCopy(fields()[16].schema(), other.plateTypeNo);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.images)) {
        this.images = data().deepCopy(fields()[17].schema(), other.images);
        fieldSetFlags()[17] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FlagCarPassListAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.leatop.bee.web.po.FlagCarPassListAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.recordNo)) {
        this.recordNo = data().deepCopy(fields()[0].schema(), other.recordNo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.picSerialNo)) {
        this.picSerialNo = data().deepCopy(fields()[1].schema(), other.picSerialNo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.flagNetRoadID)) {
        this.flagNetRoadID = data().deepCopy(fields()[2].schema(), other.flagNetRoadID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.flagRoadID)) {
        this.flagRoadID = data().deepCopy(fields()[3].schema(), other.flagRoadID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.roadId)) {
        this.roadId = data().deepCopy(fields()[4].schema(), other.roadId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.flagID)) {
        this.flagID = data().deepCopy(fields()[5].schema(), other.flagID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.posId)) {
        this.posId = data().deepCopy(fields()[6].schema(), other.posId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.laneNo)) {
        this.laneNo = data().deepCopy(fields()[7].schema(), other.laneNo);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.deviceID)) {
        this.deviceID = data().deepCopy(fields()[8].schema(), other.deviceID);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.opTime)) {
        this.opTime = data().deepCopy(fields()[9].schema(), other.opTime);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.vehPlate)) {
        this.vehPlate = data().deepCopy(fields()[10].schema(), other.vehPlate);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.vehColor)) {
        this.vehColor = data().deepCopy(fields()[11].schema(), other.vehColor);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.vehSpeed)) {
        this.vehSpeed = data().deepCopy(fields()[12].schema(), other.vehSpeed);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.vehBodyColorNo)) {
        this.vehBodyColorNo = data().deepCopy(fields()[13].schema(), other.vehBodyColorNo);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.vehBodyDeepNo)) {
        this.vehBodyDeepNo = data().deepCopy(fields()[14].schema(), other.vehBodyDeepNo);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.vehTypeNo)) {
        this.vehTypeNo = data().deepCopy(fields()[15].schema(), other.vehTypeNo);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.plateTypeNo)) {
        this.plateTypeNo = data().deepCopy(fields()[16].schema(), other.plateTypeNo);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.images)) {
        this.images = data().deepCopy(fields()[17].schema(), other.images);
        fieldSetFlags()[17] = true;
      }
    }

    /**
      * Gets the value of the 'recordNo' field.
      * @return The value.
      */
    public java.lang.Integer getRecordNo() {
      return recordNo;
    }

    /**
      * Sets the value of the 'recordNo' field.
      * @param value The value of 'recordNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setRecordNo(int value) {
      validate(fields()[0], value);
      this.recordNo = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'recordNo' field has been set.
      * @return True if the 'recordNo' field has been set, false otherwise.
      */
    public boolean hasRecordNo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'recordNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearRecordNo() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'picSerialNo' field.
      * @return The value.
      */
    public java.lang.CharSequence getPicSerialNo() {
      return picSerialNo;
    }

    /**
      * Sets the value of the 'picSerialNo' field.
      * @param value The value of 'picSerialNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setPicSerialNo(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.picSerialNo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'picSerialNo' field has been set.
      * @return True if the 'picSerialNo' field has been set, false otherwise.
      */
    public boolean hasPicSerialNo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'picSerialNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearPicSerialNo() {
      picSerialNo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagNetRoadID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagNetRoadID() {
      return flagNetRoadID;
    }

    /**
      * Sets the value of the 'flagNetRoadID' field.
      * @param value The value of 'flagNetRoadID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setFlagNetRoadID(int value) {
      validate(fields()[2], value);
      this.flagNetRoadID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'flagNetRoadID' field has been set.
      * @return True if the 'flagNetRoadID' field has been set, false otherwise.
      */
    public boolean hasFlagNetRoadID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'flagNetRoadID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearFlagNetRoadID() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagRoadID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagRoadID() {
      return flagRoadID;
    }

    /**
      * Sets the value of the 'flagRoadID' field.
      * @param value The value of 'flagRoadID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setFlagRoadID(int value) {
      validate(fields()[3], value);
      this.flagRoadID = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'flagRoadID' field has been set.
      * @return True if the 'flagRoadID' field has been set, false otherwise.
      */
    public boolean hasFlagRoadID() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'flagRoadID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearFlagRoadID() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'roadId' field.
      * @return The value.
      */
    public java.lang.Integer getRoadId() {
      return roadId;
    }

    /**
      * Sets the value of the 'roadId' field.
      * @param value The value of 'roadId'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setRoadId(int value) {
      validate(fields()[4], value);
      this.roadId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'roadId' field has been set.
      * @return True if the 'roadId' field has been set, false otherwise.
      */
    public boolean hasRoadId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'roadId' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearRoadId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagID() {
      return flagID;
    }

    /**
      * Sets the value of the 'flagID' field.
      * @param value The value of 'flagID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setFlagID(int value) {
      validate(fields()[5], value);
      this.flagID = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'flagID' field has been set.
      * @return True if the 'flagID' field has been set, false otherwise.
      */
    public boolean hasFlagID() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'flagID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearFlagID() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'posId' field.
      * @return The value.
      */
    public java.lang.Integer getPosId() {
      return posId;
    }

    /**
      * Sets the value of the 'posId' field.
      * @param value The value of 'posId'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setPosId(int value) {
      validate(fields()[6], value);
      this.posId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'posId' field has been set.
      * @return True if the 'posId' field has been set, false otherwise.
      */
    public boolean hasPosId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'posId' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearPosId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'laneNo' field.
      * @return The value.
      */
    public java.lang.Integer getLaneNo() {
      return laneNo;
    }

    /**
      * Sets the value of the 'laneNo' field.
      * @param value The value of 'laneNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setLaneNo(int value) {
      validate(fields()[7], value);
      this.laneNo = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'laneNo' field has been set.
      * @return True if the 'laneNo' field has been set, false otherwise.
      */
    public boolean hasLaneNo() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'laneNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearLaneNo() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviceID' field.
      * @return The value.
      */
    public java.lang.Integer getDeviceID() {
      return deviceID;
    }

    /**
      * Sets the value of the 'deviceID' field.
      * @param value The value of 'deviceID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setDeviceID(int value) {
      validate(fields()[8], value);
      this.deviceID = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceID' field has been set.
      * @return True if the 'deviceID' field has been set, false otherwise.
      */
    public boolean hasDeviceID() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'deviceID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearDeviceID() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'opTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getOpTime() {
      return opTime;
    }

    /**
      * Sets the value of the 'opTime' field.
      * @param value The value of 'opTime'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setOpTime(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.opTime = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'opTime' field has been set.
      * @return True if the 'opTime' field has been set, false otherwise.
      */
    public boolean hasOpTime() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'opTime' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearOpTime() {
      opTime = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehPlate' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehPlate() {
      return vehPlate;
    }

    /**
      * Sets the value of the 'vehPlate' field.
      * @param value The value of 'vehPlate'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setVehPlate(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.vehPlate = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'vehPlate' field has been set.
      * @return True if the 'vehPlate' field has been set, false otherwise.
      */
    public boolean hasVehPlate() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'vehPlate' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearVehPlate() {
      vehPlate = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehColor' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehColor() {
      return vehColor;
    }

    /**
      * Sets the value of the 'vehColor' field.
      * @param value The value of 'vehColor'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setVehColor(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.vehColor = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'vehColor' field has been set.
      * @return True if the 'vehColor' field has been set, false otherwise.
      */
    public boolean hasVehColor() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'vehColor' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearVehColor() {
      vehColor = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehSpeed' field.
      * @return The value.
      */
    public java.lang.Integer getVehSpeed() {
      return vehSpeed;
    }

    /**
      * Sets the value of the 'vehSpeed' field.
      * @param value The value of 'vehSpeed'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setVehSpeed(int value) {
      validate(fields()[12], value);
      this.vehSpeed = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'vehSpeed' field has been set.
      * @return True if the 'vehSpeed' field has been set, false otherwise.
      */
    public boolean hasVehSpeed() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'vehSpeed' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearVehSpeed() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehBodyColorNo' field.
      * @return The value.
      */
    public java.lang.Integer getVehBodyColorNo() {
      return vehBodyColorNo;
    }

    /**
      * Sets the value of the 'vehBodyColorNo' field.
      * @param value The value of 'vehBodyColorNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setVehBodyColorNo(int value) {
      validate(fields()[13], value);
      this.vehBodyColorNo = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'vehBodyColorNo' field has been set.
      * @return True if the 'vehBodyColorNo' field has been set, false otherwise.
      */
    public boolean hasVehBodyColorNo() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'vehBodyColorNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearVehBodyColorNo() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehBodyDeepNo' field.
      * @return The value.
      */
    public java.lang.Integer getVehBodyDeepNo() {
      return vehBodyDeepNo;
    }

    /**
      * Sets the value of the 'vehBodyDeepNo' field.
      * @param value The value of 'vehBodyDeepNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setVehBodyDeepNo(int value) {
      validate(fields()[14], value);
      this.vehBodyDeepNo = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'vehBodyDeepNo' field has been set.
      * @return True if the 'vehBodyDeepNo' field has been set, false otherwise.
      */
    public boolean hasVehBodyDeepNo() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'vehBodyDeepNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearVehBodyDeepNo() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehTypeNo' field.
      * @return The value.
      */
    public java.lang.Integer getVehTypeNo() {
      return vehTypeNo;
    }

    /**
      * Sets the value of the 'vehTypeNo' field.
      * @param value The value of 'vehTypeNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setVehTypeNo(int value) {
      validate(fields()[15], value);
      this.vehTypeNo = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'vehTypeNo' field has been set.
      * @return True if the 'vehTypeNo' field has been set, false otherwise.
      */
    public boolean hasVehTypeNo() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'vehTypeNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearVehTypeNo() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'plateTypeNo' field.
      * @return The value.
      */
    public java.lang.Integer getPlateTypeNo() {
      return plateTypeNo;
    }

    /**
      * Sets the value of the 'plateTypeNo' field.
      * @param value The value of 'plateTypeNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setPlateTypeNo(int value) {
      validate(fields()[16], value);
      this.plateTypeNo = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'plateTypeNo' field has been set.
      * @return True if the 'plateTypeNo' field has been set, false otherwise.
      */
    public boolean hasPlateTypeNo() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'plateTypeNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearPlateTypeNo() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'images' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getImages() {
      return images;
    }

    /**
      * Sets the value of the 'images' field.
      * @param value The value of 'images'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder setImages(java.nio.ByteBuffer value) {
      validate(fields()[17], value);
      this.images = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'images' field has been set.
      * @return True if the 'images' field has been set, false otherwise.
      */
    public boolean hasImages() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'images' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.FlagCarPassListAvro.Builder clearImages() {
      images = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FlagCarPassListAvro build() {
      try {
        FlagCarPassListAvro record = new FlagCarPassListAvro();
        record.recordNo = fieldSetFlags()[0] ? this.recordNo : (java.lang.Integer) defaultValue(fields()[0]);
        record.picSerialNo = fieldSetFlags()[1] ? this.picSerialNo : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.flagNetRoadID = fieldSetFlags()[2] ? this.flagNetRoadID : (java.lang.Integer) defaultValue(fields()[2]);
        record.flagRoadID = fieldSetFlags()[3] ? this.flagRoadID : (java.lang.Integer) defaultValue(fields()[3]);
        record.roadId = fieldSetFlags()[4] ? this.roadId : (java.lang.Integer) defaultValue(fields()[4]);
        record.flagID = fieldSetFlags()[5] ? this.flagID : (java.lang.Integer) defaultValue(fields()[5]);
        record.posId = fieldSetFlags()[6] ? this.posId : (java.lang.Integer) defaultValue(fields()[6]);
        record.laneNo = fieldSetFlags()[7] ? this.laneNo : (java.lang.Integer) defaultValue(fields()[7]);
        record.deviceID = fieldSetFlags()[8] ? this.deviceID : (java.lang.Integer) defaultValue(fields()[8]);
        record.opTime = fieldSetFlags()[9] ? this.opTime : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.vehPlate = fieldSetFlags()[10] ? this.vehPlate : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.vehColor = fieldSetFlags()[11] ? this.vehColor : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.vehSpeed = fieldSetFlags()[12] ? this.vehSpeed : (java.lang.Integer) defaultValue(fields()[12]);
        record.vehBodyColorNo = fieldSetFlags()[13] ? this.vehBodyColorNo : (java.lang.Integer) defaultValue(fields()[13]);
        record.vehBodyDeepNo = fieldSetFlags()[14] ? this.vehBodyDeepNo : (java.lang.Integer) defaultValue(fields()[14]);
        record.vehTypeNo = fieldSetFlags()[15] ? this.vehTypeNo : (java.lang.Integer) defaultValue(fields()[15]);
        record.plateTypeNo = fieldSetFlags()[16] ? this.plateTypeNo : (java.lang.Integer) defaultValue(fields()[16]);
        record.images = fieldSetFlags()[17] ? this.images : (java.nio.ByteBuffer) defaultValue(fields()[17]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FlagCarPassListAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<FlagCarPassListAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FlagCarPassListAvro>
    READER$ = (org.apache.avro.io.DatumReader<FlagCarPassListAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
