/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leatop.bee.web.po;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ImageListAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2842669879590011807L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ImageListAvro\",\"namespace\":\"com.leatop.bee.web.po\",\"fields\":[{\"name\":\"listNo\",\"type\":\"int\"},{\"name\":\"serialNo\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"flagNetRoadID\",\"type\":\"int\"},{\"name\":\"flagRoadID\",\"type\":\"int\"},{\"name\":\"flagID\",\"type\":\"int\"},{\"name\":\"deviceID\",\"type\":\"int\"},{\"name\":\"laneNo\",\"type\":\"int\"},{\"name\":\"directionNo\",\"type\":\"int\"},{\"name\":\"vehPlate\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"vehColor\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"vehSpeed\",\"type\":\"int\"},{\"name\":\"vehBodyColorNo\",\"type\":\"int\"},{\"name\":\"vehBodyDeepNo\",\"type\":\"int\"},{\"name\":\"vehTypeNo\",\"type\":\"int\"},{\"name\":\"plateTypeNo\",\"type\":\"int\"},{\"name\":\"image\",\"type\":[\"string\",\"null\"],\"default\":\"null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ImageListAvro> ENCODER =
      new BinaryMessageEncoder<ImageListAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ImageListAvro> DECODER =
      new BinaryMessageDecoder<ImageListAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ImageListAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ImageListAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ImageListAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ImageListAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ImageListAvro from a ByteBuffer. */
  public static ImageListAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int listNo;
  @Deprecated public java.lang.CharSequence serialNo;
  @Deprecated public int flagNetRoadID;
  @Deprecated public int flagRoadID;
  @Deprecated public int flagID;
  @Deprecated public int deviceID;
  @Deprecated public int laneNo;
  @Deprecated public int directionNo;
  @Deprecated public java.lang.CharSequence vehPlate;
  @Deprecated public java.lang.CharSequence vehColor;
  @Deprecated public int vehSpeed;
  @Deprecated public int vehBodyColorNo;
  @Deprecated public int vehBodyDeepNo;
  @Deprecated public int vehTypeNo;
  @Deprecated public int plateTypeNo;
  @Deprecated public java.lang.CharSequence image;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ImageListAvro() {}

  /**
   * All-args constructor.
   * @param listNo The new value for listNo
   * @param serialNo The new value for serialNo
   * @param flagNetRoadID The new value for flagNetRoadID
   * @param flagRoadID The new value for flagRoadID
   * @param flagID The new value for flagID
   * @param deviceID The new value for deviceID
   * @param laneNo The new value for laneNo
   * @param directionNo The new value for directionNo
   * @param vehPlate The new value for vehPlate
   * @param vehColor The new value for vehColor
   * @param vehSpeed The new value for vehSpeed
   * @param vehBodyColorNo The new value for vehBodyColorNo
   * @param vehBodyDeepNo The new value for vehBodyDeepNo
   * @param vehTypeNo The new value for vehTypeNo
   * @param plateTypeNo The new value for plateTypeNo
   * @param image The new value for image
   */
  public ImageListAvro(java.lang.Integer listNo, java.lang.CharSequence serialNo, java.lang.Integer flagNetRoadID, java.lang.Integer flagRoadID, java.lang.Integer flagID, java.lang.Integer deviceID, java.lang.Integer laneNo, java.lang.Integer directionNo, java.lang.CharSequence vehPlate, java.lang.CharSequence vehColor, java.lang.Integer vehSpeed, java.lang.Integer vehBodyColorNo, java.lang.Integer vehBodyDeepNo, java.lang.Integer vehTypeNo, java.lang.Integer plateTypeNo, java.lang.CharSequence image) {
    this.listNo = listNo;
    this.serialNo = serialNo;
    this.flagNetRoadID = flagNetRoadID;
    this.flagRoadID = flagRoadID;
    this.flagID = flagID;
    this.deviceID = deviceID;
    this.laneNo = laneNo;
    this.directionNo = directionNo;
    this.vehPlate = vehPlate;
    this.vehColor = vehColor;
    this.vehSpeed = vehSpeed;
    this.vehBodyColorNo = vehBodyColorNo;
    this.vehBodyDeepNo = vehBodyDeepNo;
    this.vehTypeNo = vehTypeNo;
    this.plateTypeNo = plateTypeNo;
    this.image = image;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return listNo;
    case 1: return serialNo;
    case 2: return flagNetRoadID;
    case 3: return flagRoadID;
    case 4: return flagID;
    case 5: return deviceID;
    case 6: return laneNo;
    case 7: return directionNo;
    case 8: return vehPlate;
    case 9: return vehColor;
    case 10: return vehSpeed;
    case 11: return vehBodyColorNo;
    case 12: return vehBodyDeepNo;
    case 13: return vehTypeNo;
    case 14: return plateTypeNo;
    case 15: return image;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: listNo = (java.lang.Integer)value$; break;
    case 1: serialNo = (java.lang.CharSequence)value$; break;
    case 2: flagNetRoadID = (java.lang.Integer)value$; break;
    case 3: flagRoadID = (java.lang.Integer)value$; break;
    case 4: flagID = (java.lang.Integer)value$; break;
    case 5: deviceID = (java.lang.Integer)value$; break;
    case 6: laneNo = (java.lang.Integer)value$; break;
    case 7: directionNo = (java.lang.Integer)value$; break;
    case 8: vehPlate = (java.lang.CharSequence)value$; break;
    case 9: vehColor = (java.lang.CharSequence)value$; break;
    case 10: vehSpeed = (java.lang.Integer)value$; break;
    case 11: vehBodyColorNo = (java.lang.Integer)value$; break;
    case 12: vehBodyDeepNo = (java.lang.Integer)value$; break;
    case 13: vehTypeNo = (java.lang.Integer)value$; break;
    case 14: plateTypeNo = (java.lang.Integer)value$; break;
    case 15: image = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'listNo' field.
   * @return The value of the 'listNo' field.
   */
  public java.lang.Integer getListNo() {
    return listNo;
  }

  /**
   * Sets the value of the 'listNo' field.
   * @param value the value to set.
   */
  public void setListNo(java.lang.Integer value) {
    this.listNo = value;
  }

  /**
   * Gets the value of the 'serialNo' field.
   * @return The value of the 'serialNo' field.
   */
  public java.lang.CharSequence getSerialNo() {
    return serialNo;
  }

  /**
   * Sets the value of the 'serialNo' field.
   * @param value the value to set.
   */
  public void setSerialNo(java.lang.CharSequence value) {
    this.serialNo = value;
  }

  /**
   * Gets the value of the 'flagNetRoadID' field.
   * @return The value of the 'flagNetRoadID' field.
   */
  public java.lang.Integer getFlagNetRoadID() {
    return flagNetRoadID;
  }

  /**
   * Sets the value of the 'flagNetRoadID' field.
   * @param value the value to set.
   */
  public void setFlagNetRoadID(java.lang.Integer value) {
    this.flagNetRoadID = value;
  }

  /**
   * Gets the value of the 'flagRoadID' field.
   * @return The value of the 'flagRoadID' field.
   */
  public java.lang.Integer getFlagRoadID() {
    return flagRoadID;
  }

  /**
   * Sets the value of the 'flagRoadID' field.
   * @param value the value to set.
   */
  public void setFlagRoadID(java.lang.Integer value) {
    this.flagRoadID = value;
  }

  /**
   * Gets the value of the 'flagID' field.
   * @return The value of the 'flagID' field.
   */
  public java.lang.Integer getFlagID() {
    return flagID;
  }

  /**
   * Sets the value of the 'flagID' field.
   * @param value the value to set.
   */
  public void setFlagID(java.lang.Integer value) {
    this.flagID = value;
  }

  /**
   * Gets the value of the 'deviceID' field.
   * @return The value of the 'deviceID' field.
   */
  public java.lang.Integer getDeviceID() {
    return deviceID;
  }

  /**
   * Sets the value of the 'deviceID' field.
   * @param value the value to set.
   */
  public void setDeviceID(java.lang.Integer value) {
    this.deviceID = value;
  }

  /**
   * Gets the value of the 'laneNo' field.
   * @return The value of the 'laneNo' field.
   */
  public java.lang.Integer getLaneNo() {
    return laneNo;
  }

  /**
   * Sets the value of the 'laneNo' field.
   * @param value the value to set.
   */
  public void setLaneNo(java.lang.Integer value) {
    this.laneNo = value;
  }

  /**
   * Gets the value of the 'directionNo' field.
   * @return The value of the 'directionNo' field.
   */
  public java.lang.Integer getDirectionNo() {
    return directionNo;
  }

  /**
   * Sets the value of the 'directionNo' field.
   * @param value the value to set.
   */
  public void setDirectionNo(java.lang.Integer value) {
    this.directionNo = value;
  }

  /**
   * Gets the value of the 'vehPlate' field.
   * @return The value of the 'vehPlate' field.
   */
  public java.lang.CharSequence getVehPlate() {
    return vehPlate;
  }

  /**
   * Sets the value of the 'vehPlate' field.
   * @param value the value to set.
   */
  public void setVehPlate(java.lang.CharSequence value) {
    this.vehPlate = value;
  }

  /**
   * Gets the value of the 'vehColor' field.
   * @return The value of the 'vehColor' field.
   */
  public java.lang.CharSequence getVehColor() {
    return vehColor;
  }

  /**
   * Sets the value of the 'vehColor' field.
   * @param value the value to set.
   */
  public void setVehColor(java.lang.CharSequence value) {
    this.vehColor = value;
  }

  /**
   * Gets the value of the 'vehSpeed' field.
   * @return The value of the 'vehSpeed' field.
   */
  public java.lang.Integer getVehSpeed() {
    return vehSpeed;
  }

  /**
   * Sets the value of the 'vehSpeed' field.
   * @param value the value to set.
   */
  public void setVehSpeed(java.lang.Integer value) {
    this.vehSpeed = value;
  }

  /**
   * Gets the value of the 'vehBodyColorNo' field.
   * @return The value of the 'vehBodyColorNo' field.
   */
  public java.lang.Integer getVehBodyColorNo() {
    return vehBodyColorNo;
  }

  /**
   * Sets the value of the 'vehBodyColorNo' field.
   * @param value the value to set.
   */
  public void setVehBodyColorNo(java.lang.Integer value) {
    this.vehBodyColorNo = value;
  }

  /**
   * Gets the value of the 'vehBodyDeepNo' field.
   * @return The value of the 'vehBodyDeepNo' field.
   */
  public java.lang.Integer getVehBodyDeepNo() {
    return vehBodyDeepNo;
  }

  /**
   * Sets the value of the 'vehBodyDeepNo' field.
   * @param value the value to set.
   */
  public void setVehBodyDeepNo(java.lang.Integer value) {
    this.vehBodyDeepNo = value;
  }

  /**
   * Gets the value of the 'vehTypeNo' field.
   * @return The value of the 'vehTypeNo' field.
   */
  public java.lang.Integer getVehTypeNo() {
    return vehTypeNo;
  }

  /**
   * Sets the value of the 'vehTypeNo' field.
   * @param value the value to set.
   */
  public void setVehTypeNo(java.lang.Integer value) {
    this.vehTypeNo = value;
  }

  /**
   * Gets the value of the 'plateTypeNo' field.
   * @return The value of the 'plateTypeNo' field.
   */
  public java.lang.Integer getPlateTypeNo() {
    return plateTypeNo;
  }

  /**
   * Sets the value of the 'plateTypeNo' field.
   * @param value the value to set.
   */
  public void setPlateTypeNo(java.lang.Integer value) {
    this.plateTypeNo = value;
  }

  /**
   * Gets the value of the 'image' field.
   * @return The value of the 'image' field.
   */
  public java.lang.CharSequence getImage() {
    return image;
  }

  /**
   * Sets the value of the 'image' field.
   * @param value the value to set.
   */
  public void setImage(java.lang.CharSequence value) {
    this.image = value;
  }

  /**
   * Creates a new ImageListAvro RecordBuilder.
   * @return A new ImageListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.ImageListAvro.Builder newBuilder() {
    return new com.leatop.bee.web.po.ImageListAvro.Builder();
  }

  /**
   * Creates a new ImageListAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ImageListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.ImageListAvro.Builder newBuilder(com.leatop.bee.web.po.ImageListAvro.Builder other) {
    return new com.leatop.bee.web.po.ImageListAvro.Builder(other);
  }

  /**
   * Creates a new ImageListAvro RecordBuilder by copying an existing ImageListAvro instance.
   * @param other The existing instance to copy.
   * @return A new ImageListAvro RecordBuilder
   */
  public static com.leatop.bee.web.po.ImageListAvro.Builder newBuilder(com.leatop.bee.web.po.ImageListAvro other) {
    return new com.leatop.bee.web.po.ImageListAvro.Builder(other);
  }

  /**
   * RecordBuilder for ImageListAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ImageListAvro>
    implements org.apache.avro.data.RecordBuilder<ImageListAvro> {

    private int listNo;
    private java.lang.CharSequence serialNo;
    private int flagNetRoadID;
    private int flagRoadID;
    private int flagID;
    private int deviceID;
    private int laneNo;
    private int directionNo;
    private java.lang.CharSequence vehPlate;
    private java.lang.CharSequence vehColor;
    private int vehSpeed;
    private int vehBodyColorNo;
    private int vehBodyDeepNo;
    private int vehTypeNo;
    private int plateTypeNo;
    private java.lang.CharSequence image;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.leatop.bee.web.po.ImageListAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.listNo)) {
        this.listNo = data().deepCopy(fields()[0].schema(), other.listNo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serialNo)) {
        this.serialNo = data().deepCopy(fields()[1].schema(), other.serialNo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.flagNetRoadID)) {
        this.flagNetRoadID = data().deepCopy(fields()[2].schema(), other.flagNetRoadID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.flagRoadID)) {
        this.flagRoadID = data().deepCopy(fields()[3].schema(), other.flagRoadID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.flagID)) {
        this.flagID = data().deepCopy(fields()[4].schema(), other.flagID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.deviceID)) {
        this.deviceID = data().deepCopy(fields()[5].schema(), other.deviceID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.laneNo)) {
        this.laneNo = data().deepCopy(fields()[6].schema(), other.laneNo);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.directionNo)) {
        this.directionNo = data().deepCopy(fields()[7].schema(), other.directionNo);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.vehPlate)) {
        this.vehPlate = data().deepCopy(fields()[8].schema(), other.vehPlate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.vehColor)) {
        this.vehColor = data().deepCopy(fields()[9].schema(), other.vehColor);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.vehSpeed)) {
        this.vehSpeed = data().deepCopy(fields()[10].schema(), other.vehSpeed);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.vehBodyColorNo)) {
        this.vehBodyColorNo = data().deepCopy(fields()[11].schema(), other.vehBodyColorNo);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.vehBodyDeepNo)) {
        this.vehBodyDeepNo = data().deepCopy(fields()[12].schema(), other.vehBodyDeepNo);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.vehTypeNo)) {
        this.vehTypeNo = data().deepCopy(fields()[13].schema(), other.vehTypeNo);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.plateTypeNo)) {
        this.plateTypeNo = data().deepCopy(fields()[14].schema(), other.plateTypeNo);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.image)) {
        this.image = data().deepCopy(fields()[15].schema(), other.image);
        fieldSetFlags()[15] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ImageListAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.leatop.bee.web.po.ImageListAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.listNo)) {
        this.listNo = data().deepCopy(fields()[0].schema(), other.listNo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serialNo)) {
        this.serialNo = data().deepCopy(fields()[1].schema(), other.serialNo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.flagNetRoadID)) {
        this.flagNetRoadID = data().deepCopy(fields()[2].schema(), other.flagNetRoadID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.flagRoadID)) {
        this.flagRoadID = data().deepCopy(fields()[3].schema(), other.flagRoadID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.flagID)) {
        this.flagID = data().deepCopy(fields()[4].schema(), other.flagID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.deviceID)) {
        this.deviceID = data().deepCopy(fields()[5].schema(), other.deviceID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.laneNo)) {
        this.laneNo = data().deepCopy(fields()[6].schema(), other.laneNo);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.directionNo)) {
        this.directionNo = data().deepCopy(fields()[7].schema(), other.directionNo);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.vehPlate)) {
        this.vehPlate = data().deepCopy(fields()[8].schema(), other.vehPlate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.vehColor)) {
        this.vehColor = data().deepCopy(fields()[9].schema(), other.vehColor);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.vehSpeed)) {
        this.vehSpeed = data().deepCopy(fields()[10].schema(), other.vehSpeed);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.vehBodyColorNo)) {
        this.vehBodyColorNo = data().deepCopy(fields()[11].schema(), other.vehBodyColorNo);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.vehBodyDeepNo)) {
        this.vehBodyDeepNo = data().deepCopy(fields()[12].schema(), other.vehBodyDeepNo);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.vehTypeNo)) {
        this.vehTypeNo = data().deepCopy(fields()[13].schema(), other.vehTypeNo);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.plateTypeNo)) {
        this.plateTypeNo = data().deepCopy(fields()[14].schema(), other.plateTypeNo);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.image)) {
        this.image = data().deepCopy(fields()[15].schema(), other.image);
        fieldSetFlags()[15] = true;
      }
    }

    /**
      * Gets the value of the 'listNo' field.
      * @return The value.
      */
    public java.lang.Integer getListNo() {
      return listNo;
    }

    /**
      * Sets the value of the 'listNo' field.
      * @param value The value of 'listNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setListNo(int value) {
      validate(fields()[0], value);
      this.listNo = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'listNo' field has been set.
      * @return True if the 'listNo' field has been set, false otherwise.
      */
    public boolean hasListNo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'listNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearListNo() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'serialNo' field.
      * @return The value.
      */
    public java.lang.CharSequence getSerialNo() {
      return serialNo;
    }

    /**
      * Sets the value of the 'serialNo' field.
      * @param value The value of 'serialNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setSerialNo(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.serialNo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'serialNo' field has been set.
      * @return True if the 'serialNo' field has been set, false otherwise.
      */
    public boolean hasSerialNo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'serialNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearSerialNo() {
      serialNo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagNetRoadID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagNetRoadID() {
      return flagNetRoadID;
    }

    /**
      * Sets the value of the 'flagNetRoadID' field.
      * @param value The value of 'flagNetRoadID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setFlagNetRoadID(int value) {
      validate(fields()[2], value);
      this.flagNetRoadID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'flagNetRoadID' field has been set.
      * @return True if the 'flagNetRoadID' field has been set, false otherwise.
      */
    public boolean hasFlagNetRoadID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'flagNetRoadID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearFlagNetRoadID() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagRoadID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagRoadID() {
      return flagRoadID;
    }

    /**
      * Sets the value of the 'flagRoadID' field.
      * @param value The value of 'flagRoadID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setFlagRoadID(int value) {
      validate(fields()[3], value);
      this.flagRoadID = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'flagRoadID' field has been set.
      * @return True if the 'flagRoadID' field has been set, false otherwise.
      */
    public boolean hasFlagRoadID() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'flagRoadID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearFlagRoadID() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'flagID' field.
      * @return The value.
      */
    public java.lang.Integer getFlagID() {
      return flagID;
    }

    /**
      * Sets the value of the 'flagID' field.
      * @param value The value of 'flagID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setFlagID(int value) {
      validate(fields()[4], value);
      this.flagID = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'flagID' field has been set.
      * @return True if the 'flagID' field has been set, false otherwise.
      */
    public boolean hasFlagID() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'flagID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearFlagID() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviceID' field.
      * @return The value.
      */
    public java.lang.Integer getDeviceID() {
      return deviceID;
    }

    /**
      * Sets the value of the 'deviceID' field.
      * @param value The value of 'deviceID'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setDeviceID(int value) {
      validate(fields()[5], value);
      this.deviceID = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceID' field has been set.
      * @return True if the 'deviceID' field has been set, false otherwise.
      */
    public boolean hasDeviceID() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'deviceID' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearDeviceID() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'laneNo' field.
      * @return The value.
      */
    public java.lang.Integer getLaneNo() {
      return laneNo;
    }

    /**
      * Sets the value of the 'laneNo' field.
      * @param value The value of 'laneNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setLaneNo(int value) {
      validate(fields()[6], value);
      this.laneNo = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'laneNo' field has been set.
      * @return True if the 'laneNo' field has been set, false otherwise.
      */
    public boolean hasLaneNo() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'laneNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearLaneNo() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'directionNo' field.
      * @return The value.
      */
    public java.lang.Integer getDirectionNo() {
      return directionNo;
    }

    /**
      * Sets the value of the 'directionNo' field.
      * @param value The value of 'directionNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setDirectionNo(int value) {
      validate(fields()[7], value);
      this.directionNo = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'directionNo' field has been set.
      * @return True if the 'directionNo' field has been set, false otherwise.
      */
    public boolean hasDirectionNo() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'directionNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearDirectionNo() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehPlate' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehPlate() {
      return vehPlate;
    }

    /**
      * Sets the value of the 'vehPlate' field.
      * @param value The value of 'vehPlate'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setVehPlate(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.vehPlate = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'vehPlate' field has been set.
      * @return True if the 'vehPlate' field has been set, false otherwise.
      */
    public boolean hasVehPlate() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'vehPlate' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearVehPlate() {
      vehPlate = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehColor' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehColor() {
      return vehColor;
    }

    /**
      * Sets the value of the 'vehColor' field.
      * @param value The value of 'vehColor'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setVehColor(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.vehColor = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'vehColor' field has been set.
      * @return True if the 'vehColor' field has been set, false otherwise.
      */
    public boolean hasVehColor() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'vehColor' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearVehColor() {
      vehColor = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehSpeed' field.
      * @return The value.
      */
    public java.lang.Integer getVehSpeed() {
      return vehSpeed;
    }

    /**
      * Sets the value of the 'vehSpeed' field.
      * @param value The value of 'vehSpeed'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setVehSpeed(int value) {
      validate(fields()[10], value);
      this.vehSpeed = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'vehSpeed' field has been set.
      * @return True if the 'vehSpeed' field has been set, false otherwise.
      */
    public boolean hasVehSpeed() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'vehSpeed' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearVehSpeed() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehBodyColorNo' field.
      * @return The value.
      */
    public java.lang.Integer getVehBodyColorNo() {
      return vehBodyColorNo;
    }

    /**
      * Sets the value of the 'vehBodyColorNo' field.
      * @param value The value of 'vehBodyColorNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setVehBodyColorNo(int value) {
      validate(fields()[11], value);
      this.vehBodyColorNo = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'vehBodyColorNo' field has been set.
      * @return True if the 'vehBodyColorNo' field has been set, false otherwise.
      */
    public boolean hasVehBodyColorNo() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'vehBodyColorNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearVehBodyColorNo() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehBodyDeepNo' field.
      * @return The value.
      */
    public java.lang.Integer getVehBodyDeepNo() {
      return vehBodyDeepNo;
    }

    /**
      * Sets the value of the 'vehBodyDeepNo' field.
      * @param value The value of 'vehBodyDeepNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setVehBodyDeepNo(int value) {
      validate(fields()[12], value);
      this.vehBodyDeepNo = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'vehBodyDeepNo' field has been set.
      * @return True if the 'vehBodyDeepNo' field has been set, false otherwise.
      */
    public boolean hasVehBodyDeepNo() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'vehBodyDeepNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearVehBodyDeepNo() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehTypeNo' field.
      * @return The value.
      */
    public java.lang.Integer getVehTypeNo() {
      return vehTypeNo;
    }

    /**
      * Sets the value of the 'vehTypeNo' field.
      * @param value The value of 'vehTypeNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setVehTypeNo(int value) {
      validate(fields()[13], value);
      this.vehTypeNo = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'vehTypeNo' field has been set.
      * @return True if the 'vehTypeNo' field has been set, false otherwise.
      */
    public boolean hasVehTypeNo() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'vehTypeNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearVehTypeNo() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'plateTypeNo' field.
      * @return The value.
      */
    public java.lang.Integer getPlateTypeNo() {
      return plateTypeNo;
    }

    /**
      * Sets the value of the 'plateTypeNo' field.
      * @param value The value of 'plateTypeNo'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setPlateTypeNo(int value) {
      validate(fields()[14], value);
      this.plateTypeNo = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'plateTypeNo' field has been set.
      * @return True if the 'plateTypeNo' field has been set, false otherwise.
      */
    public boolean hasPlateTypeNo() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'plateTypeNo' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearPlateTypeNo() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'image' field.
      * @return The value.
      */
    public java.lang.CharSequence getImage() {
      return image;
    }

    /**
      * Sets the value of the 'image' field.
      * @param value The value of 'image'.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder setImage(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.image = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'image' field has been set.
      * @return True if the 'image' field has been set, false otherwise.
      */
    public boolean hasImage() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'image' field.
      * @return This builder.
      */
    public com.leatop.bee.web.po.ImageListAvro.Builder clearImage() {
      image = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ImageListAvro build() {
      try {
        ImageListAvro record = new ImageListAvro();
        record.listNo = fieldSetFlags()[0] ? this.listNo : (java.lang.Integer) defaultValue(fields()[0]);
        record.serialNo = fieldSetFlags()[1] ? this.serialNo : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.flagNetRoadID = fieldSetFlags()[2] ? this.flagNetRoadID : (java.lang.Integer) defaultValue(fields()[2]);
        record.flagRoadID = fieldSetFlags()[3] ? this.flagRoadID : (java.lang.Integer) defaultValue(fields()[3]);
        record.flagID = fieldSetFlags()[4] ? this.flagID : (java.lang.Integer) defaultValue(fields()[4]);
        record.deviceID = fieldSetFlags()[5] ? this.deviceID : (java.lang.Integer) defaultValue(fields()[5]);
        record.laneNo = fieldSetFlags()[6] ? this.laneNo : (java.lang.Integer) defaultValue(fields()[6]);
        record.directionNo = fieldSetFlags()[7] ? this.directionNo : (java.lang.Integer) defaultValue(fields()[7]);
        record.vehPlate = fieldSetFlags()[8] ? this.vehPlate : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.vehColor = fieldSetFlags()[9] ? this.vehColor : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.vehSpeed = fieldSetFlags()[10] ? this.vehSpeed : (java.lang.Integer) defaultValue(fields()[10]);
        record.vehBodyColorNo = fieldSetFlags()[11] ? this.vehBodyColorNo : (java.lang.Integer) defaultValue(fields()[11]);
        record.vehBodyDeepNo = fieldSetFlags()[12] ? this.vehBodyDeepNo : (java.lang.Integer) defaultValue(fields()[12]);
        record.vehTypeNo = fieldSetFlags()[13] ? this.vehTypeNo : (java.lang.Integer) defaultValue(fields()[13]);
        record.plateTypeNo = fieldSetFlags()[14] ? this.plateTypeNo : (java.lang.Integer) defaultValue(fields()[14]);
        record.image = fieldSetFlags()[15] ? this.image : (java.lang.CharSequence) defaultValue(fields()[15]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ImageListAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<ImageListAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ImageListAvro>
    READER$ = (org.apache.avro.io.DatumReader<ImageListAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
